'use strict';const $=id=>document.getElementById(id);let selectedPacket=null,busy=false,launching=false,movementLoaded=false,movementDirty=false,movementSaving=false;
async function api(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const value=await response.json();if(!response.ok)throw Error(value.error||value.message);return value;}
async function control(body){try{$('message').className='';$('message').textContent='Working…';const result=await api('/api/control',body);$('message').textContent=result.message;poll();}catch(e){$('message').textContent=e.message;$('message').className='error';}}
function button(text,fn){const b=document.createElement('button');b.textContent=text;b.onclick=fn;return b;}
function serviceCard(s){const card=document.createElement('div');card.className='service';const name=document.createElement('h3');name.textContent=s.name;const status=document.createElement('p');status.className=s.status;status.textContent=`${s.status} · 127.0.0.1:${s.port}`;card.append(name,status);if(s.error){const e=document.createElement('pre');e.textContent=s.error;card.append(e);}if(s.name!=='dashboard')card.append(button(s.running?'Stop':'Start',()=>control({action:s.running?'stop_service':'start_service',service:s.name})));return card;}
async function poll(){if(busy)return;busy=true;try{const [state,packets,connections]=await Promise.all([api('/api/state'),api('/api/packets?limit=100'),api('/api/connections')]);$('health').textContent='Connected · C++ backend';const launch=state.client_launch||{};$('launch-status').textContent=launch.status||'Ready to start';$('launch-client').disabled=Boolean(launch.running)||launching;$('launch-client').textContent=launch.running?'Client running':launching?'Starting client…':'Start client & connect';if(launch.pid&&!$('pid').value)$('pid').value=launch.pid;$('services').replaceChildren(...state.services.map(serviceCard));renderMovement(state,connections);const g=state.geometry;$('summary').replaceChildren(...[['Online players',state.online_players],['Connections',state.connections],['Terrain tiles',g.tiles],['Colliders',g.colliders],['Stored faces',g.stored_faces],['Instance faces',g.instance_faces],['Unsupported entries',g.unsupported],['Packets',state.packet_count]].map(([label,value])=>{const e=document.createElement('span'),b=document.createElement('b');b.textContent=Number(value).toLocaleString();e.append(b,label);return e;}));$('client').textContent=JSON.stringify({client:state.client,limitations:state.limitations,geometry_error:state.geometry_error},null,2);$('connections').replaceChildren(...connections.map(c=>{const e=document.createElement('div');e.className='connection';e.textContent=`${c.peer} · ${c.phase} · ${c.id} · possession ${c.possession} · ${c.initialization||""}${c.initialization_error?" — "+c.initialization_error:""}`;return e;}));$('packets').replaceChildren(...packets.map(p=>{const tr=document.createElement('tr');for(const v of [p.id,p.channel,p.direction,p.kind]){const td=document.createElement('td');td.textContent=v;tr.append(td);}tr.onclick=()=>{selectedPacket=p;$('packet').textContent=JSON.stringify(p,null,2);$('label').value=p.label||'';$('note').value=p.annotation||'';$('confidence').value=p.confidence||'observed';};return tr;}));$('logs').replaceChildren(...['lobby','tether','world','dashboard'].map(name=>{const box=document.createElement('div');box.className='log';const title=document.createElement('h3');title.textContent=name;const pre=document.createElement('pre');pre.textContent=(state.logs[name]||[]).slice(-40).map(e=>`${new Date(e.ts*1000).toLocaleTimeString()} ${e.kind} ${JSON.stringify(e.detail)}`).join('\n');box.append(title,pre);return box;}));}catch(e){$('health').textContent='Disconnected: '+e.message;}finally{busy=false;}}
$('launch-client').onclick=async()=>{if(launching)return;launching=true;$('launch-client').disabled=true;$('launch-status').textContent='Starting local services and client…';try{const result=await api('/api/control',{action:'launch_client'});$('launch-status').textContent=result.message;$('message').className='';$('message').textContent=result.message;}catch(e){$('launch-status').textContent=e.message;$('message').textContent=e.message;$('message').className='error';}finally{launching=false;poll();}};$('start-all').onclick=()=>control({action:'start_services'});$('stop-all').onclick=()=>control({action:'stop_services'});$('reload').onclick=()=>control({action:'reload_geometry'});$('inspect').onclick=()=>control({action:'inspect_client',pid:Number($('pid').value)});$('annotate').onclick=async()=>{if(!selectedPacket)return;try{await api('/api/annotate',{packet_id:selectedPacket.id,label:$('label').value,note:$('note').value,confidence:$('confidence').value});$('message').textContent='Annotation saved';}catch(e){$('message').textContent=e.message;}};poll();setInterval(poll,1000);

function setMovementFields(settings){$('movement-speed').value=settings.speed;$('movement-collision').checked=settings.collision_enabled;$('movement-gravity').checked=settings.gravity_enabled;}
function renderMovement(state,connections=[]){
 const settings=state.movement_settings;if(!settings)return;
 if(!movementSaving&&!movementDirty)setMovementFields(settings);
 movementLoaded=true;
 const flying=!settings.gravity_enabled;const speedStatus=connections.filter(c=>c.possession).map(c=>c.speed_sync).filter(Boolean).join('; ');
 $('flight-up').disabled=$('flight-down').disabled=!flying||!state.online_players||movementSaving;
 $('movement-speed-description').textContent=`${(Number($('movement-speed').value)/100).toFixed(1)} m/s · normal forward run: 6.0 m/s`;
 if(!movementSaving&&!movementDirty)$('movement-status').textContent=`${flying?'Flying':'Gravity on'} · ${settings.speed} cm/s · collision ${settings.collision_enabled?'on':'off'} · ${state.online_players} active player${state.online_players===1?'':'s'}${speedStatus?' · '+speedStatus:''}`;
}
async function saveMovement(settings){
 if(movementSaving)return;movementSaving=true;
 for(const id of ['movement-apply','movement-fly','movement-walk','flight-up','flight-down'])$(id).disabled=true;
 $('movement-status').className='';$('movement-status').textContent='Applying movement settings…';
 try{const result=await api('/api/control',{action:'movement_settings',settings});setMovementFields(result.movement_settings);movementDirty=false;$('movement-status').textContent=result.message;}
 catch(e){$('movement-status').className='error';$('movement-status').textContent=e.message;}
 finally{movementSaving=false;for(const id of ['movement-apply','movement-fly','movement-walk'])$(id).disabled=false;poll();}
}
for(const id of ['movement-speed','movement-collision','movement-gravity'])$(id).addEventListener('input',()=>{movementDirty=true;$('movement-status').className='';$('movement-status').textContent='Changes ready to apply';$('movement-speed-description').textContent=`${(Number($('movement-speed').value)/100).toFixed(1)} m/s · normal forward run: 6.0 m/s`;});
$('movement-form').onsubmit=e=>{e.preventDefault();if(!movementLoaded)return;saveMovement({speed:Number($('movement-speed').value),collision_enabled:$('movement-collision').checked,gravity_enabled:$('movement-gravity').checked});};
$('movement-fly').onclick=()=>saveMovement({speed:Math.max(1320,Number($('movement-speed').value)||220),collision_enabled:false,gravity_enabled:false});
$('movement-walk').onclick=()=>saveMovement({speed:600,collision_enabled:true,gravity_enabled:true});
async function changeAltitude(delta){try{const result=await api('/api/control',{action:'flight_altitude',delta});$('movement-status').className='';$('movement-status').textContent=result.message;}catch(e){$('movement-status').className='error';$('movement-status').textContent=e.message;}}
$('flight-up').onclick=()=>changeAltitude(1000);$('flight-down').onclick=()=>changeAltitude(-1000);
