'use strict';
const $=id=>document.getElementById(id),canvas=$('scene'),gl=canvas.getContext('webgl',{antialias:true});
let data={players:[]},geo=null,origin=[0,0,0],target=[0,0,0],yaw=.8,pitch=.8,distance=260,selected='',geometryBusy=false,lastGeometryCentre=null,lastGeometryKey='',pollBusy=false;
const buffers={},colours=[[.40,.95,.62],[.55,.75,1],[1,.45,.65],[.9,.7,1]];
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
let program,position,matrix,colour;
if(gl){program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 p;uniform mat4 m;void main(){gl_Position=m*vec4(p,1.0);}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;uniform vec4 c;void main(){gl_FragColor=c;}'));gl.linkProgram(program);gl.useProgram(program);position=gl.getAttribLocation(program,'p');matrix=gl.getUniformLocation(program,'m');colour=gl.getUniformLocation(program,'c');gl.enableVertexAttribArray(position);gl.enable(gl.DEPTH_TEST);}else{$('error').textContent='WebGL is unavailable in this browser.';}
function upload(name,values){if(!gl)return;const old=buffers[name];const buffer=old?old.buffer:gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,values,gl.STATIC_DRAW);buffers[name]={buffer,count:values.length/3};}
function decode(text){const raw=atob(text),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const view=new DataView(bytes.buffer),floats=new Float32Array(bytes.length/4);for(let i=0;i<floats.length;i++)floats[i]=view.getFloat32(i*4,true);return floats;}
function local(p){return p.map((v,i)=>(v-origin[i])/100);}
function edgesBox(a,b,out){const pts=[];for(let n=0;n<8;n++)pts.push([0,1,2].map(i=>n&(1<<i)?b[i]:a[i]));for(let n=0;n<8;n++)for(let i=0;i<3;i++)if(!(n&(1<<i)))out.push(...pts[n],...pts[n|(1<<i)]);}
function player(){return data.players.find(p=>p.id===selected);}
async function get(url){const response=await fetch(url,{cache:'no-store'});const value=await response.json();if(!response.ok)throw Error(value.error||'Server view unavailable');return value;}
async function loadGeometry(force=false){const p=player();if(!p||geometryBusy)return;const key=JSON.stringify([p.id,p.geometry,$('radius').value,$('stride').value,$('detail').value]);if(!force&&key===lastGeometryKey&&lastGeometryCentre&&Math.hypot(p.position[0]-lastGeometryCentre[0],p.position[1]-lastGeometryCentre[1])<Number($('radius').value)*.35)return;
 geometryBusy=true;$('coverage').textContent='Loading admitted geometry…';try{const centre=p.position.slice();const q=new URLSearchParams({player:p.id,x:centre[0],y:centre[1],z:centre[2],radius:$('radius').value,stride:$('stride').value,detail:$('detail').value});const result=await get('/api/world-geometry?'+q);if(selected!==p.id)return;const oldOrigin=origin;origin=result.origin;target=target.map((v,i)=>v+(oldOrigin[i]-origin[i])/100);geo=result;upload('terrain',decode(geo.terrain));upload('collision',decode(geo.collision));const lines=[];for(const b of geo.bounds)edgesBox(local(b.minimum),local(b.maximum),lines);upload('bounds',new Float32Array(lines));lastGeometryCentre=centre;lastGeometryKey=key;$('coverage').textContent=`${geo.segments.terrain.toLocaleString()} terrain lines · ${geo.segments.collision.toLocaleString()} collision edges. ${geo.collision_detail==='full'?'Full physics edges':geo.collision_detail==='bounds'?'Collision bounds only':`Sampled physics edges + bounds (${geo.sampled_meshes} sampled bodies)`}. Terrain display samples every ${geo.terrain_stride} cells. ${Object.values(geo.clipped).some(Boolean)?'Display limit reached; some detail omitted. ':''}Bounds show the full cached extent.`;$('error').textContent='';}catch(e){$('error').textContent=e.message;}finally{geometryBusy=false;}}
async function poll(){if(pollBusy)return;pollBusy=true;try{data=await get('/api/world-view');const ids=data.players.map(p=>p.id);if(!ids.includes(selected)){selected=ids[0]||'';lastGeometryKey='';}if([...$('player').options].map(o=>o.value).join()!==ids.join()){$('player').replaceChildren(...data.players.map((p,i)=>{const o=document.createElement('option');o.value=p.id;o.textContent=`Player ${i+1} · ${p.id.slice(0,8)}`;return o;}));}$('player').value=selected;$('connection').textContent=`Live · ${ids.length} player${ids.length===1?'':'s'} · ${new Date(data.observed_at*1000).toLocaleTimeString()}`;$('empty').hidden=Boolean(ids.length);const p=player();if(p){$('stats').replaceChildren();for(const [name,value] of [['Position XYZ',p.position.map(v=>v.toFixed(1)).join(', ')],['Velocity XYZ',p.velocity.map(v=>v.toFixed(1)).join(', ')],['Movement',p.mode===1?'Grounded':p.mode===3?'Falling':`Mode ${p.mode}`],['Collision cache',`${p.tiles} tiles · ${p.colliders} colliders`]]){const dt=document.createElement('dt');dt.textContent=name;const dd=document.createElement('dd');dd.textContent=value;$('stats').append(dt,dd);}}else{geo=null;for(const b of Object.values(buffers))if(gl)gl.deleteBuffer(b.buffer);for(const key of Object.keys(buffers))delete buffers[key];$('stats').textContent='No authoritative player state';$('coverage').textContent='';lastGeometryKey='';}$('players').replaceChildren(...data.players.map((p,i)=>{const e=document.createElement('span');e.className='badge';e.style.color=`rgb(${colours[i%4].map(v=>Math.round(v*255)).join(',')})`;e.textContent=`● Player ${i+1} ${p.mode===1?'grounded':'airborne'} · Z ${p.position[2].toFixed(0)} cm`;return e;}));loadGeometry();}catch(e){$('connection').textContent='Disconnected';$('error').textContent=e.message;}finally{pollBusy=false;}}
// Row/column conventions are explicit: world XYZ is rendered with Z up.
const sub=(a,b)=>a.map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>{const n=Math.hypot(...a);return a.map(v=>v/n);};
function multiply(a,b){const r=new Float32Array(16);for(let c=0;c<4;c++)for(let row=0;row<4;row++)for(let k=0;k<4;k++)r[c*4+row]+=a[k*4+row]*b[c*4+k];return r;}
function camera(){const eye=target.map((v,i)=>v+distance*[Math.cos(yaw)*Math.cos(pitch),Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch)][i]);const z=norm(sub(eye,target)),x=norm(cross([0,0,1],z)),y=cross(z,x),view=new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);const f=1/Math.tan(.55),near=.05,far=Math.max(5000,distance*10),aspect=canvas.width/canvas.height;const projection=new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]);return multiply(projection,view);}
function draw(name,c){const b=buffers[name];if(!b)return;gl.bindBuffer(gl.ARRAY_BUFFER,b.buffer);gl.vertexAttribPointer(position,3,gl.FLOAT,false,0,0);gl.uniform4fv(colour,c);gl.drawArrays(gl.LINES,0,b.count);}
let previousFrame=0;function frame(now=0){if(now-previousFrame<33){requestAnimationFrame(frame);return;}previousFrame=now;if(gl){const dpr=Math.min(devicePixelRatio,2),w=Math.round(canvas.clientWidth*dpr),h=Math.round(canvas.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const p=player();if(p&&$('follow').checked)target=local(p.position);gl.viewport(0,0,w,h);gl.clearColor(.035,.055,.085,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(matrix,false,camera());if($('terrain').checked)draw('terrain',[.19,.54,.59,1]);if($('collision').checked)draw('collision',[.9,.61,.24,1]);if($('bounds').checked)draw('bounds',[.47,.38,.7,1]);data.players.forEach((p,i)=>{const lines=[],v=local(p.position),r=p.radius/100,hh=p.half_height/100;edgesBox([v[0]-r,v[1]-r,v[2]-hh],[v[0]+r,v[1]+r,v[2]+hh],lines);const marker=2.5;lines.push(v[0]-marker,v[1],v[2],v[0]+marker,v[1],v[2],v[0],v[1]-marker,v[2],v[0],v[1]+marker,v[2],v[0],v[1],v[2]-marker,v[0],v[1],v[2]+marker);if($('trails').checked)for(let j=1;j<p.trail.length;j++)lines.push(...local(p.trail[j-1]),...local(p.trail[j]));upload('player'+i,new Float32Array(lines));gl.disable(gl.DEPTH_TEST);draw('player'+i,[...colours[i%4],1]);gl.enable(gl.DEPTH_TEST);});}requestAnimationFrame(frame);}
let drag=null;canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,pan:e.button===2||e.shiftKey};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(drag.pan){$('follow').checked=false;target[0]+=(-Math.sin(yaw)*dx+Math.cos(yaw)*dy)*distance*.002;target[1]+=(Math.cos(yaw)*dx+Math.sin(yaw)*dy)*distance*.002;}else{yaw-=dx*.006;pitch=Math.max(.05,Math.min(1.5,pitch+dy*.006));}drag.x=e.clientX;drag.y=e.clientY;});canvas.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(3,Math.min(20000,distance*Math.exp(e.deltaY*.001)));},{passive:false});$('player').addEventListener('change',()=>{selected=$('player').value;loadGeometry(true);});for(const id of ['radius','stride','detail'])$(id).addEventListener('change',()=>loadGeometry(true));$('reload').onclick=()=>loadGeometry(true);$('recenter').onclick=()=>{$('follow').checked=true;distance=260;};poll();setInterval(poll,200);requestAnimationFrame(frame);
