#include "ashes/inspection.hpp"
#include "ashes/protocol.hpp"
#include <set>
namespace ashes {
static uint64_t number(const Json& v){return v.is_string()?std::stoull(v.get<std::string>(),nullptr,16):v.get<uint64_t>();}
Json Reflection::find_property(uint64_t actor,const std::string& name){uint64_t cls=object(actor).at("class_address");std::set<uint64_t> seen;while(cls){require(seen.insert(cls).second&&seen.size()<=32,"Class traversal bound");for(auto& prop:properties(cls))if(prop.at("name")==name){prop["owner_class"]=object(cls).at("name");return prop;}cls=r.at<uint64_t>(cls+0x60);}throw std::runtime_error("Missing current reflected property "+name);}
uint64_t Reflection::component(uint64_t actor,const std::string& name){auto p=find_property(actor,name);require(p.at("element_size")==8&&(p.at("type")=="ObjectProperty"||p.at("type")=="ObjectPropertyBase"),"Component object property required");auto value=r.at<uint64_t>(actor+p.at("offset_in_object").get<uint32_t>());require(value>0,"Component not initialized");auto j=identity(value);require(j.at("outer_address")==object(actor).at("address"),"Component ownership mismatch");return value;}
Json Reflection::network_cache(uint64_t cls,uint64_t driver){auto class_identity=object(cls);uint64_t manager=r.at<uint64_t>(driver+0x210),entries=r.at<uint64_t>(manager+8);int count=r.at<int32_t>(manager+16),capacity=r.at<int32_t>(manager+20);require(count>0&&count<=capacity&&capacity<=256,"Network cache manager map bounds");uint64_t cache=0;for(int i=0;i<count;i++){auto row=entries+size_t(i)*24;int index=r.at<int32_t>(row),serial=r.at<int32_t>(row+4);if(index==class_identity.at("object_index")&&serial==class_identity.at("serial")){cache=r.at<uint64_t>(row+8);break;}}require(cache!=0,"Class network cache not initialized");Json result={{"class",class_identity.at("name")},{"cache",cache},{"fields",Json::array()}};bool first=true;std::set<uint64_t> seen;while(cache){require(seen.insert(cache).second&&seen.size()<=32,"Network cache inheritance bound");int index=r.at<int32_t>(cache+0x10),serial=r.at<int32_t>(cache+0x14);require(index>=0&&unsigned(index)<this->count,"Cache class index");uint64_t chunk=r.at<uint64_t>(chunks+8*(unsigned(index)/65536)),class_ptr=r.at<uint64_t>(chunk+size_t(unsigned(index)%65536)*24);auto identity=object(class_ptr);require(identity.at("object_index")==index&&identity.at("serial")==serial,"Cache weak class identity");uint64_t fields=r.at<uint64_t>(cache+0x20);int count=r.at<int32_t>(cache+0x28),cap=r.at<int32_t>(cache+0x2c),base=r.at<int32_t>(cache);require(count>=0&&count<=cap&&cap<=4096&&base>=0&&base+count+1<=8193,"Network cache field bounds");if(first){result["maximum"]=base+count+1;first=false;}for(int i=0;i<count;i++){uint64_t row=fields+size_t(i)*24,tagged=r.at<uint64_t>(row),field=tagged&~1ULL;int net_index=r.at<int32_t>(row+8);require(net_index==base+i&&r.at<uint8_t>(row+16)<=1,"Network field index sequence");std::string name;uint64_t owner=0;if(tagged&1){auto obj=object(field);name=obj.at("name");owner=number(obj.at("outer_address"));auto meta=object(obj.at("class_address"));require(meta.at("name")=="Function"||meta.at("name")=="DelegateFunction","Cache UFunction tag");}else{uint32_t n=r.at<uint32_t>(field+0x20),nn=r.at<uint32_t>(field+0x24);name=this->name(n,nn);owner=r.at<uint64_t>(field+0x10)&~1ULL;auto props=properties(owner);require(std::any_of(props.begin(),props.end(),[&](auto& p){return number(p.at("address"))==field;}),"Network property reflection identity");}require(owner==class_ptr,"Network field must belong to its cache class");result["fields"].push_back({{"name",name},{"index",net_index},{"kind",(tagged&1)?"function":"property"},{"address",field},{"owner",object(owner).at("name")},{"checksum",r.at<uint32_t>(row+12)}});}cache=r.at<uint64_t>(cache+8);}return result;}
Json Reflection::scalar_handle(uint64_t actor,uint64_t driver,const std::string& field,int expected_handle){auto property=find_property(actor,field);uint64_t cls=object(actor).at("class_address"),map=r.at<uint64_t>(driver+0x5c0);int count=r.at<int32_t>(driver+0x5c8),capacity=r.at<int32_t>(driver+0x5cc);require(count>0&&count<=capacity&&capacity<=8192,"RepLayout map bounds");auto cl=object(cls);uint64_t layout=0;for(int i=0;i<count;i++){uint64_t row=map+size_t(i)*32;if(r.at<int32_t>(row)==cl.at("object_index")&&r.at<int32_t>(row+4)==cl.at("serial")){layout=r.at<uint64_t>(row+8);break;}}require(layout>0,"Current actor RepLayout missing");uint64_t commands=r.at<uint64_t>(layout+0x38);int n=r.at<int32_t>(layout+0x40),cap=r.at<int32_t>(layout+0x44);require(n>0&&n<=cap&&cap<=32768,"RepLayout command bounds");bool found=false;for(int i=0;i<n;i++){uint64_t row=commands+size_t(i)*32;if(r.at<uint64_t>(row)==number(property.at("address"))&&r.at<uint16_t>(row+0x14)==expected_handle){require(r.at<uint8_t>(row+0x1c)!=0,"Scalar traversal required");for(int j=0;j<i;j++)require(r.at<uint8_t>(commands+size_t(j)*32+0x1c)!=0,"Dynamic array before scalar handle");found=true;break;}}require(found,"Exact scalar property handle not proved");property["handle"]=expected_handle;return property;}
bool Reflection::guid_accepted(uint64_t driver,const Guid& guid,uint64_t target){
    auto identity=object(target);auto connection=r.at<uint64_t>(driver+0x138);require(connection!=0,"Current client net connection required");
    auto package=r.at<uint64_t>(connection+0x88),cache=r.at<uint64_t>(package+0x338),entries=r.at<uint64_t>(cache+0x10);
    int slots=r.at<int32_t>(cache+0x18),capacity=r.at<int32_t>(cache+0x1c);require(slots>=0&&slots<=capacity&&capacity<=100000,"GUID acceptance map bounds");
    int matches=0;
    for(int first=0;first<slots;first+=16000){int count=std::min(16000,slots-first);auto data=r.read(entries+size_t(first)*80,size_t(count)*80);
        for(int i=0;i<count;++i){auto row=data.data()+size_t(i)*80;Guid seen;int32_t index,serial;std::memcpy(&seen.object,row,8);std::memcpy(&seen.server,row+8,4);std::memcpy(&seen.random,row+12,4);std::memcpy(&index,row+16,4);std::memcpy(&serial,row+20,4);
            if(seen==guid){require(index==identity.at("object_index")&&serial>0&&serial==identity.at("serial"),"Component GUID weak identity mismatch");++matches;}
        }
    }
    require(matches<=1,"Duplicate GUID acceptance refused");return matches==1;
}

}
