#include "ashes/backend.hpp"
#ifdef _MSC_VER
using ssize_t = intptr_t;
#endif
#include <nghttp2/nghttp2.h>
#include <cstring>
namespace ashes {
static const std::string WORLD="aoc-dev-minikube-minikube",ACCOUNT="00000037000000370000003700000000",MAP="/Game/Levels/Verra_World_Master/Verra_World_Master";
Lobby::Lobby(Backend& o,Contracts& contracts):owner(o),c(contracts){auto p=owner.root/"data/characters.json";if(fs::exists(p))characters=read_json(p);else{auto frozen=read_json(owner.root/"baseline/characters.json");for(auto& r:frozen)characters.push_back(c.decode("aoc_character.Character",unhex(r.at("proto_hex"))));if(characters.empty()){characters.push_back({{"character_id",random_id()},{"character_name","LabExplorer"},{"character_name_lcase","labexplorer"},{"account_id",ACCOUNT},{"world_id",WORLD},{"version",1},{"revision",1},{"record_status","active"},{"character_info",{{"level",1},{"primary_class",1},{"gender",1},{"race",1},{"json_blob_map",{{"map",{{"CustomizationDataKey","{\"presetGuid\":\"0\",\"randomSeed\":1454,\"gender\":\"Male\",\"race\":\"Kaelar\",\"class\":\"Fighter\",\"skinSet\":2,\"faceMorphWeightMaps\":{},\"sectionsValues\":{},\"decalData\":[],\"decalBlendGroups\":[],\"bIsHelmetVisible\":true,\"bIsCapeVisible\":true}"}}}}}}}});}save();}}
void Lobby::save(){write_file(owner.root/"data/characters.json",characters.dump(2));}
std::vector<Json> Lobby::process(const Json& request,Json& session){std::string name=request.value("message_type_name","");Json payload;try{payload=c.decode(name,unhex(request.value("message_data","")));}catch(...){return {Json{{"message_type_name",name},{"status_code",30}}};}std::string shortname=name.substr(name.find_last_of('.')+1),replyname=name;auto at=replyname.find("Request");if(at!=std::string::npos)replyname.replace(at,7,"Reply");auto wrap=[&](const std::string& n,const Json& p,int status=0){Json system=request.value("system_data",Json::object());system["tags"]["server_tracking_id"]=std::to_string(uint64_t(wall_time()*1e9));return Json{{"message_type_name",n},{"message_data",hex(c.encode(n,p))},{"status_code",status},{"system_data",system}};};auto worlds=[&](){return Json{{"worlds",Json::array({{{"world_id",WORLD},{"world_display_name","Ashes C++ Lab"},{"available",true},{"character_count",characters.size()}}})}};};Json reply;
if(shortname=="SessionRequest"){bool open=payload.value("request_type",0)==1;session["open"]=open;Json tags=payload.value("tags",Json::object());tags["account_id"]=ACCOUNT;tags["session_token"]=random_id();reply={{"request_type",payload.value("request_type",0)},{"result_code",0},{"tags",tags},{"data_map",{{"ics_ping_client_config.json","{\"ping_period_msec\":1000,\"ping_hosts\":[\"127.0.0.1\"]}"},{"server_time",std::to_string(uint64_t(wall_time()*1000))}}},{"data_string",open?"session_opened":"session_closed"}};if(open){Json minis=Json::array();for(auto& ch:characters)minis.push_back({{"character_id",ch.at("character_id")},{"character_name",ch.at("character_name")},{"world_id",WORLD}});auto state=c.encode("ics_xclient.PlayerSessionState",{{"character_mini_records",minis}});reply["data_map"]["player_session_state"]=std::string(state.begin(),state.end());owner.event("session_request",{{"service","lobby"}});}return {wrap(replyname,reply)};}
if(shortname=="KeepAliveMessage")return {wrap(name,payload)};if(!session.value("open",false))return {wrap(name,payload,43)};
if(shortname=="CheckGameVersionRequest")reply={{"supported",true},{"message","Local C++ lab client"}};else if(shortname=="GetWorldsRequest")reply=worlds();else if(shortname=="GameClientInterestEvent")return {wrap("ics_xclient.WorldStatusEvent",worlds())};else if(shortname=="GetCharactersRequest"){reply={{"characters",Json::array()}};for(auto& ch:characters)if(ch.value("world_id",WORLD)==payload.value("world_id",WORLD))reply["characters"].push_back(ch);}else if(shortname=="CheckCharacterNameRequest"){std::string n=payload.value("character_name","");bool available=!n.empty();for(auto& ch:characters)if(_stricmp(n.c_str(),ch.at("character_name").get<std::string>().c_str())==0)available=false;reply={{"character_name",n},{"available",available}};}else if(shortname=="CreateCharacterRequest"){std::string n=payload.value("character_name","");if(n.empty()||payload.value("world_id","")!=WORLD)return {wrap(name,payload,24)};for(auto& ch:characters)if(_stricmp(n.c_str(),ch.at("character_name").get<std::string>().c_str())==0)return {wrap(name,payload,24)};auto info=payload.value("create_character_info",Json::object());info["level"]=1;Json ch={{"character_id",random_id()},{"character_name",n},{"world_id",WORLD},{"account_id",ACCOUNT},{"version",1},{"revision",1},{"record_status","active"},{"created_msec",uint64_t(wall_time()*1000)},{"character_info",info}};characters.push_back(ch);save();reply=ch;}else if(shortname=="SelectCharacterRequest"||shortname=="PlayRequest"||shortname=="CanDeleteCharacterRequest"||shortname=="DeleteCharacterRequest"){auto ch=std::find_if(characters.begin(),characters.end(),[&](auto& value){return value.at("character_id")==payload.value("character_id","");});if(ch==characters.end())return {wrap(name,payload,59)};if(shortname=="PlayRequest"){if(payload.value("world_id","")!=WORLD)return {wrap(name,payload,24)};auto token=random_id();tokens[token]={ch->at("character_id"),mono_time()+120};reply={{"game_connection_token",token},{"game_connection_string","127.0.0.1:"+std::to_string(owner.world.port)+"?map="+MAP+"&driver=/Script/IntrepidNet.IntrepidNetDriver&world_id="+WORLD+"&EncryptionToken="+token}};owner.event("play_requested",{{"service","lobby"},{"character_id",ch->at("character_id")}});}else{reply={{"character_id",ch->at("character_id")}};if(shortname=="CanDeleteCharacterRequest")reply["can_delete"]=true;else if(shortname=="DeleteCharacterRequest"){characters.erase(ch);save();}else session["character_id"]=ch->at("character_id");}}else if(shortname=="AuthRefreshRequest")reply={{"auth_token",random_id()},{"refresh_token",random_id()}};else if(shortname=="PlayEndRequest")reply=Json::object();else return {wrap(name,payload,23)};return {wrap(replyname,reply)};}
struct GrpcStream {Json session={{"open",false}};Bytes input,output;size_t output_pos=0;bool headers=false,end=false;std::string path;};
struct GrpcConnection {Lobby& lobby;SOCKET socket;nghttp2_session* h2=nullptr;std::map<int32_t,GrpcStream> streams;};
static ssize_t send_callback(nghttp2_session*,const uint8_t* data,size_t length,int,void* opaque){auto& conn=*static_cast<GrpcConnection*>(opaque);try{send_all(conn.socket,data,length);return ssize_t(length);}catch(...){return NGHTTP2_ERR_CALLBACK_FAILURE;}}
static ssize_t read_callback(nghttp2_session* h2,int32_t stream,uint8_t* buffer,size_t length,uint32_t* flags,nghttp2_data_source*,void* opaque){auto& conn=*static_cast<GrpcConnection*>(opaque);auto& s=conn.streams.at(stream);size_t n=std::min(length,s.output.size()-s.output_pos);if(n){std::memcpy(buffer,s.output.data()+s.output_pos,n);s.output_pos+=n;return ssize_t(n);}if(s.end){*flags|=NGHTTP2_DATA_FLAG_EOF|NGHTTP2_DATA_FLAG_NO_END_STREAM;nghttp2_nv trailer{reinterpret_cast<uint8_t*>(const_cast<char*>("grpc-status")),reinterpret_cast<uint8_t*>(const_cast<char*>("0")),11,1,NGHTTP2_NV_FLAG_NONE};nghttp2_submit_trailer(h2,stream,&trailer,1);return 0;}return NGHTTP2_ERR_DEFERRED;}
static int header_callback(nghttp2_session*,const nghttp2_frame* frame,const uint8_t* name,size_t nl,const uint8_t* value,size_t vl,uint8_t,void* opaque){auto& conn=*static_cast<GrpcConnection*>(opaque);if(std::string(reinterpret_cast<const char*>(name),nl)==":path")conn.streams[frame->hd.stream_id].path.assign(reinterpret_cast<const char*>(value),vl);return 0;}
static int data_callback(nghttp2_session* h2,uint8_t,int32_t stream,const uint8_t* data,size_t n,void* opaque){auto& conn=*static_cast<GrpcConnection*>(opaque);auto& s=conn.streams[stream];if(s.path!="/ics_xclient.XClientService/ProcessXClientMessage")return NGHTTP2_ERR_CALLBACK_FAILURE;if(s.input.size()+n>4*1024*1024)return NGHTTP2_ERR_CALLBACK_FAILURE;s.input.insert(s.input.end(),data,data+n);try{while(s.input.size()>=5){require(s.input[0]==0,"Compressed gRPC message unsupported");uint32_t size=(uint32_t(s.input[1])<<24)|(uint32_t(s.input[2])<<16)|(uint32_t(s.input[3])<<8)|s.input[4];require(size<=4*1024*1024,"gRPC message budget");if(s.input.size()<size_t(size)+5)break;Bytes payload(s.input.begin()+5,s.input.begin()+5+size);s.input.erase(s.input.begin(),s.input.begin()+5+size);auto request=conn.lobby.c.decode("ics_common.MessageWrapper",payload);std::lock_guard lock(conn.lobby.owner.mutex);conn.lobby.owner.record("lobby","C2S",payload,request);for(auto& response:conn.lobby.process(request,s.session)){auto b=conn.lobby.c.encode("ics_common.MessageWrapper",response);conn.lobby.owner.record("lobby","S2C",b,response);s.output.push_back(0);for(int i=3;i>=0;i--)s.output.push_back(uint8_t(b.size()>>(i*8)));s.output.insert(s.output.end(),b.begin(),b.end());}}if(!s.headers){auto nv=[](const char* n,const char* v){return nghttp2_nv{reinterpret_cast<uint8_t*>(const_cast<char*>(n)),reinterpret_cast<uint8_t*>(const_cast<char*>(v)),std::strlen(n),std::strlen(v),NGHTTP2_NV_FLAG_NONE};};nghttp2_nv headers[]={nv(":status","200"),nv("content-type","application/grpc"),nv("grpc-encoding","identity")};nghttp2_data_provider provider{};provider.read_callback=read_callback;require(nghttp2_submit_response(h2,stream,headers,3,&provider)==0,"gRPC response submit failed");s.headers=true;}else nghttp2_session_resume_data(h2,stream);return 0;}catch(const std::exception& e){conn.lobby.owner.event("lobby_error",{{"reason",e.what()}});return NGHTTP2_ERR_CALLBACK_FAILURE;}}
static int frame_callback(nghttp2_session* h2,const nghttp2_frame* f,void* opaque){auto& c=*static_cast<GrpcConnection*>(opaque);if((f->hd.type==NGHTTP2_DATA||f->hd.type==NGHTTP2_HEADERS)&&(f->hd.flags&NGHTTP2_FLAG_END_STREAM)){auto& s=c.streams[f->hd.stream_id];s.end=true;nghttp2_session_resume_data(h2,f->hd.stream_id);}return 0;}
static int close_callback(nghttp2_session*,int32_t stream,uint32_t,void* opaque){static_cast<GrpcConnection*>(opaque)->streams.erase(stream);return 0;}
void Lobby::serve(SOCKET socket){GrpcConnection conn{*this,socket};nghttp2_session_callbacks* callbacks=nullptr;nghttp2_session_callbacks_new(&callbacks);nghttp2_session_callbacks_set_send_callback(callbacks,send_callback);nghttp2_session_callbacks_set_on_header_callback(callbacks,header_callback);nghttp2_session_callbacks_set_on_data_chunk_recv_callback(callbacks,data_callback);nghttp2_session_callbacks_set_on_frame_recv_callback(callbacks,frame_callback);nghttp2_session_callbacks_set_on_stream_close_callback(callbacks,close_callback);nghttp2_session_server_new(&conn.h2,callbacks,&conn);nghttp2_session_callbacks_del(callbacks);nghttp2_settings_entry settings[]={{NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS,32}};nghttp2_submit_settings(conn.h2,NGHTTP2_FLAG_NONE,settings,1);nghttp2_session_send(conn.h2);std::array<uint8_t,65536> data;while(owner.lobby_service.running){int n=recv(socket,reinterpret_cast<char*>(data.data()),int(data.size()),0);if(n<=0)break;if(nghttp2_session_mem_recv(conn.h2,data.data(),size_t(n))<0||nghttp2_session_send(conn.h2)<0)break;}nghttp2_session_del(conn.h2);}
}
