#include "ashes/protocol.hpp"
#include <openssl/hmac.h>
#include <windows.h>
#include <cstring>
#include <sstream>
#include <iomanip>
#include <algorithm>
namespace ashes {
template<class T>static T scalar(const Bytes& b){T v;require(b.size()==sizeof(v),"Scalar size");std::memcpy(&v,b.data(),sizeof(v));require(std::isfinite(double(v)),"Nonfinite scalar");return v;}
template<class T>static Bytes bytes(T v){Bytes b(sizeof(v));std::memcpy(b.data(),&v,sizeof(v));return b;}
BitWriter& BitWriter::write(uint64_t v,size_t n){require(n<=64&&(n==64||v<(uint64_t(1)<<n)),"Bit field overflow");for(size_t i=0;i<n;i++){if(bits/8==data.size())data.push_back(0);data[bits/8]|=uint8_t(((v>>i)&1)<<(bits%8));bits++;}return *this;}
BitWriter& BitWriter::raw(const Bytes& b,size_t n){require(n<=b.size()*8,"Raw bit count");for(size_t i=0;i<n;i++)write((b[i/8]>>(i%8))&1,1);return *this;}
BitWriter& BitWriter::packed(uint32_t v){while(v>=128){write(((v&127)<<1)|1,8);v>>=7;}return write(v<<1,8);}
BitWriter& BitWriter::bounded(uint32_t v,uint64_t maximum){require(maximum>=1&&maximum<=0x100000000ULL&&v<maximum,"Bounded integer");uint64_t partial=0;for(uint64_t mask=1;partial+mask<maximum;mask<<=1){bool b=v&mask;write(b,1);partial|=b?mask:0;}return *this;}
BitWriter& BitWriter::string(const std::string& s){if(s.empty())return write(0,32);bool ascii=std::all_of(s.begin(),s.end(),[](unsigned char c){return c<128;});if(ascii){write(s.size()+1,32);Bytes b(s.begin(),s.end());b.push_back(0);return raw(b);}int n=MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),int(s.size()),nullptr,0);require(n>0,"Invalid UTF8");std::wstring w(n,0);MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),int(s.size()),w.data(),n);write(uint32_t(-int32_t(n+1)),32);Bytes b((n+1)*2);std::memcpy(b.data(),w.data(),n*2);return raw(b);}
Bytes BitWriter::finish(int n){for(int i=0;i<n;i++)write(1,1);return data;}
BitReader::BitReader(const Bytes& b,size_t n):data(b),limit(n){require(n<=b.size()*8,"Bit limit");}uint64_t BitReader::read(size_t n){require(n<=64&&n<=remaining(),"Truncated field at bit "+std::to_string(pos));uint64_t v=0;for(size_t i=0;i<n;i++)v|=uint64_t((data[(pos+i)/8]>>((pos+i)%8))&1)<<i;pos+=n;return v;}Bytes BitReader::raw(size_t n){require(n<=remaining(),"Truncated raw field");BitWriter w;for(size_t i=0;i<n;i++)w.write(read(1),1);return w.data;}uint32_t BitReader::packed(){uint64_t v=0;for(int s=0;s<35;s+=7){auto b=read(8);v|=(b>>1)<<s;require(v<=0xffffffff,"Packed overflow");if(!(b&1))return uint32_t(v);}throw std::runtime_error("Overlong packed integer");}uint32_t BitReader::bounded(uint64_t maximum){require(maximum>=1&&maximum<=0x100000000ULL,"Invalid bound");uint64_t v=0;for(uint64_t m=1;v+m<maximum;m<<=1)v|=read(1)*m;return uint32_t(v);}
std::string BitReader::string(){auto n=int32_t(read(32));if(!n)return {};require(std::abs(int64_t(n))<=16384,"FString safety bound");auto b=raw(size_t(std::abs(n))*(n<0?16:8));require(b.back()==0&&(n>=0||b[b.size()-2]==0),"FString missing terminator");if(n>0)return std::string(b.begin(),b.end()-1);auto* w=reinterpret_cast<const wchar_t*>(b.data());int m=WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,w,-n-1,nullptr,0,nullptr,nullptr);require(m>=0,"Invalid UTF16");std::string s(m,0);WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,w,-n-1,s.data(),m,nullptr,nullptr);return s;}
void Guid::write(BitWriter& w)const{w.write(object,64).write(server,32).write(random,32);}Json Guid::json()const{std::ostringstream s;s<<"0x"<<std::hex<<std::setw(16)<<std::setfill('0')<<object;return {{"object_id",s.str()},{"server_id",server},{"randomizer",random}};}Guid Guid::from(const Json& j){return {std::stoull(j.at("object_id").get<std::string>(),nullptr,16),j.at("server_id"),j.at("randomizer")};}Guid Guid::fresh(){auto b=random_bytes(12);uint64_t o;uint32_t r;std::memcpy(&o,b.data(),8);std::memcpy(&r,b.data()+8,4);return {(o&0x7ffffffffffffffeULL)|2,1,r};}
static std::string control_name(int id){switch(id){case 0:return "Hello";case 1:return "Welcome";case 3:return "Challenge";case 4:return "NetSpeed";case 5:return "Login";case 6:return "Failure";case 9:return "Join";case 15:return "Skip";case 16:return "Abort";case 19:return "DebugText";case 21:return "SecurityViolation";default:return "Unknown_"+std::to_string(id);}}
static Json controls(const Bytes& b,size_t n){BitReader r(b,n);Json result=Json::array();while(r.remaining()){int id=int(r.read(8));Json m={{"id",id},{"name",control_name(id)}};switch(id){case 0:m["endian"]=r.read(8);m["network_version"]=r.read(32);m["encryption_token"]=r.string();m["network_features"]=r.read(16);break;case 3:case 6:case 19:case 21:m["text"]=r.string();break;case 1:m["map"]=r.string();m["game_mode"]=r.string();m["redirect"]=r.string();break;case 4:m["rate"]=r.read(32);break;case 5:m["response"]=r.string();m["url"]=r.string();m["unique_id_flags"]=r.read(8);if(m["unique_id_flags"]==8){m["unique_id"]=r.string();m["unique_id_type"]=r.string();}else m["unresolved_tail_hex"]=hex(r.raw(r.remaining()));break;case 9:case 15:case 16:break;default:m["unresolved_tail_hex"]=hex(r.raw(r.remaining()));}result.push_back(m);}return result;}
Json decode_packet(const Bytes& data,bool server,unsigned maximum){try{require(data.size()>=5&&Bytes(data.begin(),data.begin()+4)==unhex("96760c50"),"AoC magic mismatch");require(data.back()!=0,"Missing packet termination");size_t n=(data.size()-1)*8;uint8_t last=data.back();while(last>>1){last>>=1;n++;}BitReader r(data,n);r.read(32);Json j={{"protocol","aoc_unreal_udp"},{"session_id",r.read(2)},{"client_id",r.read(3)},{"handshake",bool(r.read(1))},{"wire_bytes",data.size()}};if(j["handshake"]==true){j["restart"]=bool(r.read(1));j["min_version"]=r.read(8);j["version"]=r.read(8);j["packet_type"]=r.read(8);j["sent_count"]=r.read(8);j["network_version"]=r.read(32);j["network_features"]=r.read(16);j["secret_id"]=r.read(1);j["timestamp"]=scalar<double>(r.raw(64));j["cookie"]=hex(r.raw(160));j["extension_bits"]=r.remaining();j["extension_hex"]=hex(r.raw(r.remaining()));j["kind"]="stateless."+std::array<std::string,4>{"Initial","Challenge","Response","Ack"}.at(j["packet_type"]);return j;}
require(r.remaining()>0&&((data[(r.limit-1)/8]>>((r.limit-1)%8))&1),"Missing NetConnection termination");r.limit--;uint32_t p=uint32_t(r.read(32));int words=(p&15)+1;require(words<=8,"Ack history window");j["sequence"]=(p>>18)&16383;j["ack"]=(p>>4)&16383;j["ack_history"]=Json::array();for(int i=0;i<words;i++)j["ack_history"].push_back(r.read(32));j["custom_header_opaque"]=r.read(48);j["has_packet_info"]=bool(r.read(1));if(j["has_packet_info"]==true){j["jitter_clock"]=r.read(10);j["has_server_frame_time"]=bool(r.read(1));if(server&&j["has_server_frame_time"]==true)j["server_frame_time_ms"]=r.read(8);}j["bunches"]=Json::array();std::string names;bool close=false;while(r.remaining()){Json b;auto start=r.pos;bool c=r.read(1);bool opened=c?r.read(1):false,closed=c?r.read(1):false;if(closed)require(r.read(4)==0,"Unproved close reason");b["open"]=opened;b["close"]=closed;b["paused"]=bool(r.read(1));b["reliable"]=bool(r.read(1));b["channel"]=r.packed();b["exports"]=bool(r.read(1));b["must_map"]=bool(r.read(1));b["partial"]=bool(r.read(1));b["reliable_sequence"]=b["reliable"]==true?Json(r.read(10)):Json();b["partial_flags"]=Json::array();if(b["partial"]==true)for(int i=0;i<3;i++)b["partial_flags"].push_back(r.read(1));b["channel_name"]=nullptr;if(b["reliable"]==true||opened){if(r.read(1))b["channel_name"]=r.packed();else{b["channel_name"]={{"string",r.string()},{"number",r.read(32)}};}}size_t a=r.pos;size_t count=r.bounded(maximum);b["payload_length_field_bits"]=r.pos-a;b["payload_bits"]=count;b["start_bit"]=start;auto payload=r.raw(count);b["payload_hex"]=hex(payload);if(closed){require(b["channel"]==0&&!opened&&b["reliable"]==true&&b["channel_name"]==255&&b["exports"]==false&&b["must_map"]==false&&b["partial"]==false&&count==0,"Unproved channel close");close=true;}if(b["channel"]==0&&b["exports"]==false&&b["partial"]==false){b["messages"]=controls(payload,count);for(auto& m:b["messages"]){if(!names.empty())names+="+";names+=m["name"].get<std::string>();}}j["bunches"].push_back(b);}require(!close||j["bunches"].size()==1,"Mixed channel close");j["kind"]=close?"control.Close":!names.empty()?"control."+names:j["bunches"].empty()?"game.ack":"game.bunch";j["payload_length_max"]=maximum;return j;}catch(const std::exception& e){if(maximum==8224){auto alt=decode_packet(data,server,8192);if(!alt.contains("error"))return alt;}return {{"kind","game.decode_error"},{"error",e.what()},{"wire_bytes",data.size()}};}}
Bytes encode_control(int id,const Json& j){BitWriter w;w.write(id,8);switch(id){case 0:w.write(1,8).write(j.at("network_version"),32).string("").write(0,16);break;case 1:w.string(j.at("map")).string(j.at("game_mode")).string(j.value("redirect",""));break;case 3:case 6:w.string(j.value("text",""));break;case 4:w.write(j.value("rate",200000),32);break;case 5:w.string(j.value("response","")).string(j.value("url","?Name=LocalExplorer")).write(8,8).string(j.value("unique_id","LocalExplorer")).string("NULL");break;case 9:break;default:throw std::runtime_error("Unsupported control");}return w.data;}
static void write_bunch(BitWriter& w,const Json& b){bool o=b.value("open",false),c=b.value("close",false),reliable=b.value("reliable",true),partial=b.value("partial",false);w.write(o||c,1);if(o||c)w.write(o,1).write(c,1);if(c)w.write(0,4);w.write(0,1).write(reliable,1).packed(b.value("channel",0)).write(b.value("exports",false),1).write(b.value("must_map",false),1).write(partial,1);if(reliable)w.write(b.at("reliable_sequence").get<unsigned>()&1023,10);if(partial)for(auto f:b.at("partial_flags"))w.write(f,1);if(reliable||o)w.write(1,1).packed(b.value("channel_name",255));auto p=unhex(b.at("payload_hex"));auto n=b.value("payload_bits",p.size()*8);w.bounded(unsigned(n),8224).raw(p,n);}
Bytes encode_packet(int s,int c,int seq,int ack,const std::vector<uint32_t>& history,const Json& bunches,std::optional<uint64_t> info){require(!history.empty()&&history.size()<=8,"History bound");BitWriter w;w.raw(unhex("96760c50")).write(s,2).write(c,3).write(0,1).write((uint32_t(seq&16383)<<18)|(uint32_t(ack&16383)<<4)|uint32_t(history.size()-1),32);for(auto h:history)w.write(h,32);w.write(info.value_or(0),48).write(info.has_value(),1);if(info)w.write(uint64_t(mono_time()*1000)&1023,10).write(0,1);for(auto& b:bunches)write_bunch(w,b);return w.finish(2);}
Bytes encode_handshake(const Json& j,int type,double timestamp,const Bytes& cookie){BitWriter w;w.raw(unhex("96760c50")).write(j.at("session_id"),2).write(j.at("client_id"),3).write(1,1).write(0,1).write(j.at("min_version"),8).write(j.at("version"),8).write(type,8).write(j.at("sent_count"),8).write(j.at("network_version"),32).write(j.at("network_features"),16).write(type==3,1).raw(bytes(timestamp)).raw(cookie).raw(unhex(j.value("extension_hex","")));return w.finish(1);}
Bits actor_rpc(int index,int maximum,const Bits& a){BitWriter f;f.bounded(index,maximum).packed(unsigned(a.bits)).raw(a.data,a.bits);BitWriter w;w.write(0,1).write(1,1).packed(unsigned(f.bits)).raw(f.data,f.bits);return {w.data,w.bits};}
Json decode_actor_rpc(const Bytes& b,size_t n,int maximum){BitReader r(b,n);require(!r.read(1)&&r.read(1),"RPC-only flags required");require(r.packed()==r.remaining(),"RPC block length");Json result=Json::array();while(r.remaining()){auto index=r.bounded(maximum),count=r.packed();result.push_back({{"field_index",index},{"argument_bits",count},{"argument_hex",hex(r.raw(count))}});}return result;}
static Vec vector(BitReader& r,double scale){auto h=r.bounded(128);unsigned w=h&63;Vec v;if(!w){for(auto& x:v)x=(h>>6)?scalar<double>(r.raw(64)):scalar<float>(r.raw(32));}else for(auto& x:v){auto b=r.read(w);int64_t s=int64_t(b);if(b&(1ULL<<(w-1)))s-=int64_t(1ULL<<w);x=double(s)/((h>>6)?scale:1);}return v;}
static Json move(BitReader& r,const std::string& kind){Json j={{"kind",kind},{"timestamp",scalar<float>(r.raw(32))}};j["acceleration"]=vector(r,10);j["client_location"]=vector(r,100);Vec rotation{};for(auto& v:rotation)if(r.read(1))v=r.read(16)*360./65536;j["control_rotation"]=rotation;j["compressed_flags"]=r.read(1)?r.read(8):0;require(!r.read(1)&&!r.read(1),"Movement base/bone requires reviewed codec");j["movement_mode"]=r.read(1)?r.read(8):1;j["custom_axis_sign_bits"]=Json::array();for(int i=0;i<4;i++)j["custom_axis_sign_bits"].push_back(r.read(1));return j;}
Json decode_move_argument(const Bytes& b,size_t n){BitReader outer(b,n);require(outer.read(1)==1,"Missing packed argument");auto count=outer.packed();require(count>=1&&count<=8192&&count==outer.remaining(),"Packed movement length");BitReader r(outer.raw(count),count);Json moves=Json::array();moves.push_back(move(r,"new"));bool pending=r.read(1);if(pending){r.read(1);moves.push_back(move(r,"pending"));}if(r.read(1))moves.push_back(move(r,"old"));r.read(1);require(r.remaining()==0,"Trailing movement bits");return moves;}
Bits move_ack(float t){require(std::isfinite(t),"Finite timestamp required");BitWriter i;i.write(1,1).raw(bytes(t));BitWriter a;a.write(1,1).packed(unsigned(i.bits)).raw(i.data,i.bits);return actor_rpc(35,198,{a.data,a.bits});}
Bits move_correction(float t,Vec p,Vec v,int mode){require(std::isfinite(t)&&finite(p)&&finite(v)&&(mode==1||mode==3||mode==5),"Correction bounds");BitWriter i;i.write(0,1).raw(bytes(t)).write(0,4);for(double d:p)i.raw(bytes(d));for(double d:v)i.raw(bytes(d));i.write(0,3).write(mode!=1,1);if(mode!=1)i.write(mode,8);i.write(0,2);BitWriter a;a.write(1,1).packed(unsigned(i.bits)).raw(i.data,i.bits);return actor_rpc(35,198,{a.data,a.bits});}
static Bits actor_property(BitWriter& s){BitWriter w;w.write(1,1).write(1,1).packed(unsigned(s.bits)).raw(s.data,s.bits);return {w.data,w.bits};}Bits role_content(){BitWriter s;s.write(0,1).packed(8).write(2,3).packed(0);return actor_property(s);}Bits begin_play_content(){BitWriter s;s.write(0,1).packed(21).write(1,1).packed(0);return actor_property(s);}Bits state_link(Guid g,int handle){BitWriter s;s.write(0,1).packed(handle);g.write(s);s.packed(0);return actor_property(s);}
static Bits subobject(Guid g,BitWriter& content,bool properties=true){BitWriter w;w.write(properties,1).write(0,1);g.write(w);w.write(1,1).packed(unsigned(content.bits)).raw(content.data,content.bits);return {w.data,w.bits};}Bits subobject_empty(Guid g){BitWriter c;c.write(0,1).packed(0);return subobject(g,c);}Bits character_name(Guid g,const std::string& n){require(!n.empty()&&n.size()<=64&&std::all_of(n.begin(),n.end(),[](unsigned char c){return std::isalnum(c)&&c<128;}),"ASCII character name bound");BitWriter c;c.write(0,1).packed(8).string(n).packed(0);return subobject(g,c);}Bits character_id(Guid g,const std::string& id){require(id.size()==32&&unhex(id).size()==16,"Character ID bound");BitWriter c;c.write(0,1);for(int n=0;n<4;n++)c.packed(3+n).write(std::stoul(id.substr(n*8,8),nullptr,16),32);c.packed(0);return subobject(g,c);}static Bits stat_delta(Guid g,uint64_t record,uint32_t value,int array_key,int base_key,int item_id,bool supports_delta_struct){require(array_key>base_key&&base_key>=0&&item_id>0,"Stat update keys required");BitWriter d;d.write(supports_delta_struct,1).write(array_key,32).write(base_key,32).write(0,32).write(1,32).write(item_id,32).write(record,64).write(value,32);BitWriter c;c.bounded(6,23).packed(unsigned(d.bits)).raw(d.data,d.bits);return subobject(g,c,false);}
Bits stat_update(Guid g,uint64_t record,uint32_t value,int array_key,int base_key,int item_id){return stat_delta(g,record,value,array_key,base_key,item_id,false);}
Bits stat_content(Guid g,uint64_t record,uint32_t value,int key){return stat_delta(g,record,value,key,key-1,key,true);}
struct Ref {Guid guid;std::string path;std::shared_ptr<Ref> outer;uint32_t checksum=0;bool no_load=false,has_checksum=false;void write(BitWriter& w)const{guid.write(w);if(guid.object==0&&guid.server==0&&guid.random==0)return;unsigned flags=(!path.empty()?1:0)|(no_load?2:0)|(has_checksum?4:0);w.write(flags,8);if(flags&1){if(outer)outer->write(w);else Guid{}.write(w);w.string(path);if(flags&4)w.write(checksum,32);}}};
static Ref ref(uint64_t id,const std::string& path,uint32_t checksum=0,std::shared_ptr<Ref> outer={},bool no_load=false){return {{id,0,0},path,std::move(outer),checksum,no_load,checksum!=0};}
static Bits exports(const std::vector<Ref>& refs){BitWriter w;w.write(0,1).write(refs.size(),32);for(auto& r:refs)r.write(w);return {w.data,w.bits};}
Bits stat_export(Guid p,Guid g){Ref parent{p,"",{},0,true,false};Ref r{g,"StatsComponent",std::make_shared<Ref>(parent),4031330514u,true,true};return exports({r});}Bits character_export(Guid p,Guid g){Ref parent{p,"",{},0,true,false};Ref r{g,"BaseCharacterInfo",std::make_shared<Ref>(parent),2952361071u,true,true};return exports({r});}
static Ref level_ref(){auto map=std::make_shared<Ref>(ref(0xb359315214b240a7ULL,"/Game/Levels/Verra_World_Master/Verra_World_Master",0,{},true));auto world=std::make_shared<Ref>(ref(0xe66eea9dcf2327d1ULL,"Verra_World_Master",0,map,true));return ref(0xe42f6afe6ac5e219ULL,"PersistentLevel",0,world,true);}
static Json bunch(int channel,int seq,const Bits& payload,bool reliable=true){return {{"channel",channel},{"channel_name",102},{"reliable",reliable},{"reliable_sequence",seq&1023},{"payload_hex",hex(payload.data)},{"payload_bits",payload.bits}};}static Json creation(int initial,int channel,Guid actor,Ref archetype,std::optional<Vec> location,bool controller){Ref level=level_ref();Bits ex=exports({archetype,level});BitWriter w;actor.write(w);archetype.guid.write(w);level.guid.write(w);if(location){w.write(1,1).write(1,1);std::array<int64_t,3>a;int n=1;for(int i=0;i<3;i++){a[i]=int64_t(std::floor(std::abs((*location)[i])*10+.5))*((*location)[i]<0?-1:1);uint64_t t=uint64_t(std::abs(a[i]));int k=1;while(t){k++;t>>=1;}n=std::max(n,k);}require(n<=63,"Spawn range");w.write(n|64,7);for(auto v:a)w.write(uint64_t(v)&((1ULL<<n)-1),n);}else w.write(0,1);w.write(0,3);if(controller)w.write(0,8);Json first=bunch(channel,initial+1,ex),last=bunch(channel,initial+2,{w.data,w.bits});first["partial"]=last["partial"]=true;first["open"]=true;first["exports"]=true;first["partial_flags"]={1,0,0};last["partial_flags"]={0,0,1};return Json::array({first,last});}
Json controller_bunches(int initial,Guid actor){auto package=std::make_shared<Ref>(ref(0x388a0ee91474b469ULL,"/Game/ThirdPersonCPP/Blueprints/AoCPlayerControllerBP"));return creation(initial,3,actor,ref(0x309fd7f5912a3c33ULL,"Default__AoCPlayerControllerBP_C",0x6b62891c,package),{},true);}
Json scene_bunches(int initial,const std::string& kind,Guid actor,Vec p){uint64_t package,id;uint32_t sum;int channel;std::string path,name;if(kind=="game_state"){package=0xc6546cc4140f45c3ULL;id=0x72516bac9471f0e3ULL;sum=0x01442053;channel=5;path="/Game/GameBlueprints/AoCGameStateBP";name="Default__AoCGameStateBP_C";}else if(kind=="pawn"){package=0x888d5ab23568d817ULL;id=0x817231b97e0ae84bULL;sum=0x02cdc5b6;channel=9;path="/Game/ThirdPersonCPP/Blueprints/PlayerPawn";name="Default__PlayerPawn_C";}else{package=0x1ae80686e8b97865ULL;id=0xde917003ba3b725fULL;sum=0xf4f44182;channel=39;path="/Game/ThirdPersonCPP/Blueprints/AoCPlayerStateBP";name="Default__AoCPlayerStateBP_C";}return creation(initial,channel,actor,ref(id,name,sum,std::make_shared<Ref>(ref(package,path))),kind=="pawn"?std::optional<Vec>(p):std::nullopt,false);}
Bits object_argument(Guid g){BitWriter w;w.write(1,1);g.write(w);return {w.data,w.bits};}Json hud_bunches(int last,int index,int maximum){auto hud=ref(0x7574e081758a110fULL,"BP_AOCHUD_C",0xac6f1251,std::make_shared<Ref>(ref(0x6c5157f1ebbf3de7ULL,"/Game/UI/Widgets/BP_AOCHUD")));Json first=bunch(3,last+1,exports({hud})),second=bunch(3,last+2,actor_rpc(index,maximum,object_argument(hud.guid)));first["partial"]=second["partial"]=true;first["exports"]=true;first["partial_flags"]={1,0,0};second["partial_flags"]={0,0,1};return Json::array({first,second});}
Bytes WorldProtocol::cookie(const std::string& host,uint16_t port,double timestamp)const{std::string peer="('"+host+"', "+std::to_string(port)+")";Bytes b(peer.begin(),peer.end());auto t=bytes(timestamp);b.insert(b.end(),t.begin(),t.end());Bytes result(20);unsigned n=0;HMAC(EVP_sha1(),secret.data(),int(secret.size()),b.data(),b.size(),result.data(),&n);return result;}
Bytes WorldProtocol::send(Connection& c,const Json& bs){std::vector<uint32_t> h(8);for(int i=0;i<256;i++)if(c.history[i])h[i/32]|=uint32_t(1)<<(i%32);while(h.size()>1&&h.back()==0)h.pop_back();auto data=encode_packet(c.session,c.client,c.out_seq,c.in_seq,h,bs,c.info);Json pending=Json::array();for(auto& b:bs)if(b.value("reliable",true)){c.channel_reliable[b.value("channel",0)]=b.at("reliable_sequence");pending.push_back(b);}if(!pending.empty()){c.pending[c.out_seq]=pending;c.pending_at[c.out_seq]=mono_time();}c.out_seq=(c.out_seq+1)&16383;return data;}
std::vector<Bytes> WorldProtocol::bootstrap(Connection& c,Vec p){require(c.phase=="joined"&&c.actors.empty(),"Fresh joined connection required");int initial=int(c.cookie[0]|c.cookie[1]<<8)&1023;std::vector<Bytes> out;auto pc=Guid::fresh();c.actors["controller"]=pc;out.push_back(send(c,controller_bunches(initial,pc)));for(auto kind:{"game_state","pawn","player_state"}){auto g=Guid::fresh();c.actors[kind]=g;out.push_back(send(c,scene_bunches(initial,kind,g,p)));}return out;}
std::vector<Bytes> WorldProtocol::handle(const Bytes& data,const std::string& host,uint16_t port){auto p=decode_packet(data);if(p.contains("error")){event("udp_decode_error",p);return {};}double now=mono_time();std::string peer=host+":"+std::to_string(port);for(auto it=connections.begin();it!=connections.end();)if(now-it->second.last_seen>120){event("udp_connection_expired",{{"connection_id",it->second.id}});it=connections.erase(it);}else ++it;
if(p["handshake"]==true){if(p["restart"]==true||(p["version"]!=3&&p["version"]!=4)||p["network_features"]!=0)return {};int type=p["packet_type"];if(type==0){double t=wall_time();return {encode_handshake(p,1,t,cookie(host,port,t))};}if(type!=2)return {};double t=p.at("timestamp");auto ck=unhex(p.at("cookie"));auto expected=cookie(host,port,t);if(wall_time()-t<0||wall_time()-t>30||ck.size()!=20||CRYPTO_memcmp(ck.data(),expected.data(),20))return {};auto old=connections.find(peer);if(old!=connections.end()&&old->second.cookie==ck){if(old->second.session!=p["session_id"]||old->second.client!=p["client_id"])return {};old->second.last_seen=now;}else{if(old!=connections.end()&&t<=old->second.handshake_time)return {};if(old==connections.end()&&connections.size()>=64)return {};Connection c;c.cookie=ck;c.session=p["session_id"];c.client=p["client_id"];int server=ck[0]|ck[1]<<8,client=ck[2]|ck[3]<<8;c.out_seq=server&16383;c.in_seq=(client-1)&16383;c.out_reliable=server&1023;c.in_reliable=client&1023;c.handshake_time=t;connections[peer]=c;event("udp_handshake",{{"connection_id",c.id},{"peer",peer}});}return {encode_handshake(p,3,-1,ck)};}
auto it=connections.find(peer);if(it==connections.end())return {};auto& c=it->second;c.last_seen=now;if(c.session!=p["session_id"]||c.client!=p["client_id"])return {};if(c.phase=="closed")return {send(c)};int delta=(p.at("sequence").get<int>()-c.in_seq)&16383;if(delta==0)return {send(c)};if(delta>=8192)return {};for(auto a=c.pending.begin();a!=c.pending.end();){unsigned distance=(p.at("ack").get<int>()-a->first)&16383;auto& h=p.at("ack_history");if(distance<h.size()*32&&(h[distance/32].get<uint32_t>()>>(distance%32)&1)){c.pending_at.erase(a->first);a=c.pending.erase(a);}else ++a;}c.in_seq=p["sequence"];c.history<<=std::min(delta,256);c.history.set(0);c.info=p.at("custom_header_opaque").get<uint64_t>();std::vector<Bytes> out;
for(auto& b:p["bunches"]){if(b["channel"]!=0||!b.contains("messages"))continue;if(b["reliable"]==true){int seq=b["reliable_sequence"];int expected=(c.in_reliable+1)&1023;int backwards=(c.in_reliable-seq)&1023;if(backwards<512)continue;if(seq!=expected){c.history.reset(0);continue;}c.in_reliable=seq;}if(b["close"]==true){c.phase="closed";c.pending.clear();event("udp_connection_closed",{{"connection_id",c.id}});continue;}for(auto& m:b["messages"]){int id=m["id"];std::optional<Bytes> reply;if(id==0&&c.phase=="connected"){c.phase="challenged";reply=encode_control(3,{{"text",random_id(8)}});}else if(id==5&&(c.phase=="challenged"||c.phase=="connected")){c.phase="welcomed";reply=encode_control(1,{{"map","/Game/Levels/Verra_World_Master/Verra_World_Master"},{"game_mode","/Game/GameBlueprints/AoCGameModeBaseBP.AoCGameModeBaseBP_C"}});event("welcome",{{"connection_id",c.id}});}else if(id==9&&c.phase=="welcomed"){c.phase="joined";event("join",{{"connection_id",c.id},{"peer",peer}});}if(reply){c.out_reliable=(c.out_reliable+1)&1023;Json bs=Json::array({{{"channel",0},{"channel_name",255},{"reliable",true},{"reliable_sequence",c.out_reliable},{"payload_hex",hex(*reply)}}});out.push_back(send(c,bs));}}}
std::vector<int> retry;for(auto& [seq,at]:c.pending_at)if(now-at>.35)retry.push_back(seq);for(int seq:retry){auto bs=c.pending.at(seq);c.pending.erase(seq);c.pending_at.erase(seq);out.push_back(send(c,bs));if(out.size()>8)break;}if(out.empty())out.push_back(send(c));return out;}
}
