#include "ashes/backend.hpp"
#include <sstream>
#include <bit>
namespace ashes {
static uint64_t address_of(const Json& j){return std::stoull(j.at("address").get<std::string>(),nullptr,16);}
static double movement_float(Reflection& f,uint64_t component,const std::string& name){auto p=f.find_property(component,name);require(p.at("type")=="FloatProperty"&&p.at("element_size")==4,"Native movement scalar required");double value=f.r.at<float>(component+p.at("offset_in_object").get<unsigned>());require(std::isfinite(value)&&value>=0&&value<=100000,"Native movement scalar bounds");return value;}
static void code_matches(ProcessReader& r,uint64_t rva,const std::string& value){auto expected=unhex(value);require(r.read(r.base+rva,expected.size())==expected,"Reviewed code bytes changed");}
static void virtual_matches(ProcessReader& r,uint64_t object,size_t offset,uint64_t rva){require(r.at<uint64_t>(r.at<uint64_t>(object)+offset)==r.base+rva,"Reviewed current virtual target changed");}
static uint8_t movement_input_gate(Reflection& f,uint64_t controller){
 virtual_matches(f.r,controller,0xb70,0x44119b0);virtual_matches(f.r,controller,0x910,0x3ef5810);virtual_matches(f.r,controller,0x918,0x3ef23f0);virtual_matches(f.r,controller,0x920,0x3eea250);
 code_matches(f.r,0x44119b0,"488b0148ffa010090000");code_matches(f.r,0x3ef5810,"0fb681f90300000fb6d2448d0455ffffffff33d24403c04585c0410fb6c00f4fd08891f9030000c3");code_matches(f.r,0x3ef23f0,"c681f903000000c3");code_matches(f.r,0x3eea250,"80b9f9030000000f97c0c3");
 // This byte is native controller storage proved by the complete virtual leaves, not an FProperty.
 return f.r.at<uint8_t>(controller+0x3f9);
}
static Json idle_loading_pose(Reflection& f,uint64_t player,const Vec& spawn,bool grounded=false){
 auto root=f.component(player,"RootComponent"),cm=f.component(player,"CharacterMovement");auto parent=f.find_property(root,"AttachParent"),location=f.find_property(root,"RelativeLocation"),velocity=f.find_property(cm,"Velocity"),mode=f.find_property(cm,"MovementMode");
 require(parent.at("element_size")==8&&f.r.at<uint64_t>(root+parent.at("offset_in_object").get<unsigned>())==0,"Unattached loading root required");
 require(location.at("type")=="StructProperty"&&location.at("element_size")==24&&velocity.at("type")=="StructProperty"&&velocity.at("element_size")==24&&mode.at("type")=="ByteProperty"&&mode.at("element_size")==1,"Current reflected loading pose layout required");
 auto position=f.r.at<Vec>(root+location.at("offset_in_object").get<unsigned>()),speed=f.r.at<Vec>(cm+velocity.at("offset_in_object").get<unsigned>());auto state=f.r.at<uint8_t>(cm+mode.at("offset_in_object").get<unsigned>());
 require(finite(position)&&finite(speed)&&length(sub(position,spawn))<5&&length(speed)<.001&&(grounded?state==1:(state==1||state==3)),"Idle native pawn at supported spawn required before gameplay release");
 return {{"position",position},{"velocity",speed},{"movement_mode",state}};
}
static Json loading_floor_contact(Reflection& f,uint64_t cm){
 auto prop=f.find_property(cm,"CurrentFloor");require(prop.at("type")=="StructProperty"&&prop.at("element_size")==272,"Current reflected FindFloorResult required");auto structure=f.r.at<uint64_t>(address_of(prop)+0x70);require(f.identity(structure,"ScriptStruct").at("name")=="FindFloorResult","Exact native floor struct required");
 auto base=cm+prop.at("offset_in_object").get<unsigned>();auto before=f.r.read(base,272);auto fields=f.properties(structure);
 auto field=[](const Json& fields,const std::string& name){auto it=std::find_if(fields.begin(),fields.end(),[&](const Json& p){return p.at("name")==name;});require(it!=fields.end(),"Native floor field missing: "+name);return *it;};
 auto boolean=[&](uint64_t base,const Json& fields,const std::string& name){auto p=field(fields,name);require(p.at("type")=="BoolProperty"&&p.at("element_size")==1,"Native floor BoolProperty required");auto layout=f.r.read(address_of(p)+0x70,4);require(layout[0]==1&&layout[3],"Current floor bool mask required");return (f.r.at<uint8_t>(base+p.at("offset_in_object").get<unsigned>()+layout[1])&layout[3])!=0;};
 require(boolean(base,fields,"bBlockingHit")&&boolean(base,fields,"bWalkableFloor"),"Native walkable blocking floor required before releasing input");auto hit=field(fields,"HitResult");require(hit.at("type")=="StructProperty"&&hit.at("element_size")==256,"Native floor hit result layout required");auto hit_base=base+hit.at("offset_in_object").get<unsigned>();auto hit_type=f.r.at<uint64_t>(address_of(hit)+0x70);require(f.identity(hit_type,"ScriptStruct").at("name")=="HitResult","Exact native hit struct required");auto hit_fields=f.properties(hit_type);
 require(boolean(hit_base,hit_fields,"bBlockingHit")&&!boolean(hit_base,hit_fields,"bStartPenetrating"),"Native floor must block without penetration");auto component=field(hit_fields,"Component");require(component.at("type")=="WeakObjectProperty"&&component.at("element_size")==8,"Native floor component weak field required");auto weak=hit_base+component.at("offset_in_object").get<unsigned>();int index=f.r.at<int32_t>(weak),serial=f.r.at<int32_t>(weak+4);require(index>=0&&unsigned(index)<f.count&&serial>0,"Native floor component lifetime required");auto chunk=f.r.at<uint64_t>(f.chunks+8*(unsigned(index)/65536));auto pointer=f.r.at<uint64_t>(chunk+size_t(unsigned(index)%65536)*24);auto identity=f.identity(pointer,"PrimitiveComponent");require(identity.at("object_index")==index&&identity.at("serial")==serial,"Native floor weak identity changed");require(f.r.read(base,272)==before,"Native cached floor changed during readiness verification");return {{"blocking",true},{"walkable",true},{"penetrating",false},{"component",identity}};
}
static void frozen_code_matches(Backend& owner,ProcessReader& r,uint64_t rva,const std::string& file,size_t size=0){auto expected=read_file(owner.root/"baseline/evidence"/file);if(size){require(expected.size()>=size,"Frozen code range truncated");expected.resize(size);}require(!expected.empty()&&r.read(r.base+rva,expected.size())==expected,"Current code differs from frozen reviewed range");}
static bool bool_field(Reflection& f,uint64_t actor,const std::string& name){auto p=f.find_property(actor,name);require(p.at("type")=="BoolProperty","Reflected BoolProperty required");auto data=f.r.read(address_of(p)+0x70,4);require(data[0]==1&&data[3]>0,"Reflected bool scalar mask");return (f.r.at<uint8_t>(actor+p.at("offset_in_object").get<unsigned>()+data[1])&data[3])!=0;}
static Json accepted(const Json& snapshot,Guid guid,const std::string& cls){std::vector<Json> matches;for(auto& m:snapshot.at("network_guid_actor_matches"))if(m.at("guid")==guid.json())matches.push_back(m);require(matches.size()==1,"Exactly one current network GUID match required");auto m=matches.front();require(m.at("actor").at("class")==cls&&m.at("weak_object_index")==m.at("actor").at("object_index")&&m.at("weak_object_serial").get<int>()>0,"Accepted actor weak identity/class mismatch");return m;}
static void verify_character_guid_layout(Reflection& f,uint64_t info,uint64_t driver){
 auto prop=f.property(info,"CharacterGuid",0x118,16);require(prop.at("type")=="StructProperty","Reflected character Guid struct required");auto structure=f.r.at<uint64_t>(address_of(prop)+0x70);require(f.object(structure).at("name")=="Guid","Exact native Guid struct required");auto fields=f.properties(structure);require(fields.size()==4,"Exactly four native Guid words required");
 auto cls=f.object(f.object(info).at("class_address"));auto map=f.r.at<uint64_t>(driver+0x5c0);int count=f.r.at<int32_t>(driver+0x5c8),capacity=f.r.at<int32_t>(driver+0x5cc);require(count>0&&count<=capacity&&capacity<=8192,"CharacterInfo layout map bounds");uint64_t layout=0;
 for(int i=0;i<count;i++){auto row=map+size_t(i)*32;if(f.r.at<int32_t>(row)==cls.at("object_index")&&f.r.at<int32_t>(row+4)==cls.at("serial")){require(!layout,"Unique CharacterInfo layout required");layout=f.r.at<uint64_t>(row+8);}}
 require(layout,"Current CharacterInfo layout required");auto commands=f.r.at<uint64_t>(layout+0x38);int n=f.r.at<int32_t>(layout+0x40),cap=f.r.at<int32_t>(layout+0x44);require(n>=6&&n<=cap&&cap<=32768,"Bounded expanded Guid layout required");
 for(int i=0;i<4;i++){std::string name(1,char('A'+i));auto field=std::find_if(fields.begin(),fields.end(),[&](const Json& row){return row.at("name")==name;});require(field!=fields.end()&&field->at("type")=="IntProperty"&&field->at("element_size")==4&&field->at("array_dim")==1&&field->at("offset_in_object")==i*4,"Exact native Guid child word required");auto row=commands+size_t(i+2)*32;require(f.r.at<uint64_t>(row)==address_of(*field)&&f.r.at<uint16_t>(row+0x14)==i+3&&f.r.at<uint16_t>(row+0x16)==2&&f.r.at<uint8_t>(row+0x1c)==5&&f.r.at<int32_t>(row+0xc)==0x118+i*4,"Exact expanded Guid child wire handles 3..6 required");}
 for(int i=0;i<6;i++)require(f.r.at<uint8_t>(commands+size_t(i)*32+0x1c)!=0,"No dynamic arrays before Guid words");virtual_matches(f.r,info,0x560,0x6c2b0c0);
}
void dispatch_stage(Backend& owner,Connection& c,const Json& snapshot,const std::string& stage){require(!c.stages.contains(stage),"Initialization stage already consumed");ProcessReader r(owner.attached.at("pid"),owner.config.at("client_exe").get<std::string>(),owner.config.at("client_sha256"));verify_evidence(r.proof(),snapshot);Reflection f(r);auto pc=accepted(snapshot,c.actors.at("controller"),"AoCPlayerControllerBP_C"),pawn=accepted(snapshot,c.actors.at("pawn"),"PlayerPawn_C"),gs=accepted(snapshot,c.actors.at("game_state"),"AoCGameStateBP_C"),ps=accepted(snapshot,c.actors.at("player_state"),"AoCPlayerStateBP_C");auto cache=pc.at("guid_cache");require(cache==pawn.at("guid_cache")&&cache==gs.at("guid_cache")&&cache==ps.at("guid_cache"),"All initialized actors must share current GUID cache");auto level=pc.at("actor").at("outer_address");for(auto m:{pawn,gs,ps})require(m.at("actor").at("outer_address")==level,"Actors must share accepted level");uint64_t controller=address_of(pc.at("actor")),player=address_of(pawn.at("actor")),game_state=address_of(gs.at("actor"));for(auto m:{pc,pawn,gs,ps}){auto live=f.identity(address_of(m.at("actor")));require(live.at("object_index")==m.at("weak_object_index")&&live.at("serial")==m.at("weak_object_serial"),"Current actor lifetime changed");}
uint64_t driver=0;for(auto& d:snapshot.at("net_drivers"))if(d.value("guid_cache","")==cache.get<std::string>()){require(driver==0,"Unique owning net driver required");driver=address_of(d);}require(driver>0,"Owning current net driver missing");auto class_cache=f.network_cache(f.object(controller).at("class_address"),driver);int maximum=class_cache.at("maximum");require(maximum==1032,"Exact controller class RPC maximum required");auto rpc=[&](const std::string& name,int index,const std::string& cls){auto fields=class_cache.at("fields");require(std::count_if(fields.begin(),fields.end(),[&](auto& v){return v.at("name")==name&&v.at("index")==index&&v.at("owner")==cls&&v.at("kind")=="function";})==1,"Exact live function cache field required "+name);};auto send=[&](int channel,const Bits& b){owner.send_world(c,Json::array({{{"channel",channel},{"channel_name",102},{"reliable",true},{"reliable_sequence",(c.channel_reliable.at(channel)+1)&1023},{"payload_hex",hex(b.data)},{"payload_bits",b.bits}}}));};
if(stage=="LoadingInputLock"||stage=="LoadingInputLocked"||stage=="LoadingInputRelock"||stage=="LoadingInputRelocked"||stage=="LoadingInputRelease"||stage=="WorldReady"){
 require(f.guid_accepted(driver,c.actors.at("controller"),controller),"Current accepted controller GUID required for input gate");
 auto counter=movement_input_gate(f,controller);
 if(stage=="LoadingInputRelock"||stage=="LoadingInputRelocked"||stage=="LoadingInputRelease"||stage=="WorldReady"){
  require(c.possession&&c.stages.contains("ClientRestart"),"Acknowledged possession required after restart");f.property(controller,"Pawn",0x3a8,8);f.property(controller,"AcknowledgedPawn",0x428,8);f.property(player,"Controller",0x398,8);
  require(r.at<uint64_t>(controller+0x3a8)==player&&r.at<uint64_t>(controller+0x428)==player&&r.at<uint64_t>(player+0x398)==controller,"Current mutual possession required for loading gate");
 }
 if(stage=="LoadingInputLock"||stage=="LoadingInputRelock"||stage=="LoadingInputRelease"){
  rpc("ClientIgnoreMoveInput",34,"PlayerController");auto fields=class_cache.at("fields");auto it=std::find_if(fields.begin(),fields.end(),[](const Json& row){return row.at("name")=="ClientIgnoreMoveInput";});
  require(it!=fields.end()&&it->at("checksum")==898884168,"Reviewed input gate function checksum required");uint64_t function=it->at("address");f.identity(function,"Function");
  require(r.at<uint32_t>(function+0xd0)==0x1020cc2&&r.at<int32_t>(function+0x78)==1&&r.at<uint64_t>(function+0xf8)==r.base+0x4442390,"Current reliable client input RPC binding required");
  auto parameters=f.properties(function);require(parameters.size()==1,"Single input RPC boolean required");auto param=parameters[0];
  require(param.at("name")=="bIgnore"&&param.at("type")=="BoolProperty"&&param.at("offset_in_object")==0&&param.at("element_size")==1&&param.at("array_dim")==1,"Exact native input boolean parameter required");auto layout=r.read(address_of(param)+0x70,4);require(layout[0]==1&&layout[1]==0&&layout[3]==255,"Native boolean mask required");
  if(stage=="LoadingInputLock"){require(!c.stages.contains("ClientRestart")&&counter==0,"Fresh unlocked controller before possession required");send(3,ignore_move_input(true));}
  else if(stage=="LoadingInputRelock"){require(c.stages.contains("LoadingInputLocked")&&r.at<uint8_t>(player+0x1f8)==1&&counter<=1,"Previous loading lock and simulated pawn required after possession reset");if(counter==0)send(3,ignore_move_input(true));owner.event("loading_input_relocked",{{"connection_id",c.id},{"counter_before",counter},{"rpc_sent",counter==0},{"reason","ClientRestart possession can reset native input counters"}});}
  else{require(c.stages.contains("GameplayPresentationReady")&&c.stages.contains("PawnAutonomous")&&c.stages.contains("NativeMovementReady")&&c.stages.contains("ActivateMovement")&&c.possession&&owner.players.contains(c.id)&&counter==1&&r.at<uint8_t>(player+0x1f8)==2,"Ready autonomous pawn, presentation and paired lock required before release");send(3,ignore_move_input(false));}
 }else if(stage=="LoadingInputLocked"||stage=="LoadingInputRelocked"){require(c.stages.contains(stage=="LoadingInputLocked"?"LoadingInputLock":"LoadingInputRelock")&&counter==1,"Native input lock acknowledgement required");}
 else{require(c.stages.contains("LoadingInputRelease")&&c.stages.contains("ActivateMovement")&&counter==0&&r.at<uint8_t>(player+0x1f8)==2,"Native input release and autonomy readback required");owner.event("loading_input_released",{{"connection_id",c.id},{"native_counter",counter},{"role",2},{"floor_ready",c.stages.contains("WinsteadCollisionAdmitted")}});}
}
else if(stage=="NodeLayoutProbe"){
 require(c.stages.contains("GameStateBeginPlay")&&c.possession&&c.stages.contains("LoadingInputRelocked")&&movement_input_gate(f,controller)==1&&r.at<uint8_t>(player+0x1f8)==1&&bool_field(f,game_state,"bReplicatedHasBegunPlay"),"BegunPlay possessed simulated pawn with locked movement required for metadata probe");
 require(!c.actors.contains("node_probe")&&!c.channel_reliable.contains(42),"Fresh unused metadata probe channel required");
 require(!owner.players.contains(c.id),"Metadata must start before server movement preparation");
 uint64_t cls=0;
 for(unsigned i=0;i<std::min(f.count,65536u);i++){
  auto chunk=r.at<uint64_t>(f.chunks+8*(i/65536));auto a=r.at<uint64_t>(chunk+size_t(i%65536)*24);if(!a)continue;
  auto obj=f.object(a);if(obj.at("name")!="NodeLayoutReplicator")continue;
  require(f.identity(a).at("class")=="Class","Exact native settlement class required");cls=a;break;
 }
 require(cls>0&&f.object(r.at<uint64_t>(cls+0x20)).at("name")=="/Script/GameSystemsPlugin","Native settlement script package required");
 auto ctor=r.at<uint64_t>(cls+0xd0);require(ctor==r.base+0x5b79900,"Reviewed settlement constructor pointer required");code_matches(r,0x5b79900,"488b014885c0740b488bd1488bc8e93d9fa000c3");
 auto cdo=r.at<uint64_t>(cls+0x150);auto identity=f.identity(cdo,"NodeLayoutReplicator");require(identity.at("name")=="Default__NodeLayoutReplicator"&&identity.at("class_address")==cls,"Exact settlement CDO required");
 require(r.at<uint64_t>(cdo)==r.base+0xb4a11e8,"Reviewed settlement primary vtable required");virtual_matches(r,cdo,0x2a8,0x3bca830);virtual_matches(r,cdo,0x2b0,0x65a9260);
 require(f.property(cdo,"NodeGuid",0x500,8).at("type")=="Int64Property"&&f.property(cdo,"LayoutAssetSetGuids",0x370,0x190).at("type")=="StructProperty","Reviewed settlement reflected fields required");
 require(r.at<uint64_t>(cdo+0x500)==0&&r.at<uint8_t>(cdo+0x508)==0&&r.at<int32_t>(cdo+0x480)==0,"Empty nonloading settlement defaults required");
 auto root=f.component(cdo,"RootComponent");require(f.identity(root,"SceneComponent").at("outer_address")==identity.at("address"),"Reviewed default scene root required");
 auto static_guid=[](){auto g=Guid::fresh();return Guid{g.object|1,0,0};};auto actor=Guid::fresh(),package=static_guid(),archetype=static_guid();
 auto packet=node_probe_bunches(int(c.cookie[0]|c.cookie[1]<<8)&1023,actor,package,archetype,owner.config.at("spawn").get<Vec>());
 owner.send_world(c,packet);c.actors["node_probe"]=actor;
 owner.event("settlement_metadata_probe_authored",{{"connection_id",c.id},{"actor_guid",actor.json()},{"package_guid",package.json()},{"archetype_guid",archetype.json()},{"channel",42},{"driver",driver},{"node_guid",0},{"asset_grant",false},{"client_acceptance_verified",false}});
}
else if(stage=="NodeLayoutWinsteadFloor"){
 require(c.stages.contains("NodeLayoutProbe")&&c.stages.contains("GameStateBeginPlay")&&c.possession&&movement_input_gate(f,controller)==1&&r.at<uint8_t>(player+0x1f8)==1,"Accepted empty probe and locked simulated pawn required");
 require(!owner.players.contains(c.id),"Floor packet must precede movement preparation");
 auto node_match=accepted(snapshot,c.actors.at("node_probe"),"NodeLayoutReplicator");require(node_match.at("guid_cache")==cache&&node_match.at("actor").at("outer_address")==level,"Settlement probe must share current driver/level");
 auto actor=address_of(node_match.at("actor"));auto identity=f.identity(actor,"NodeLayoutReplicator");require(identity.at("object_index")==node_match.at("weak_object_index")&&identity.at("serial")==node_match.at("weak_object_serial")&&f.guid_accepted(driver,c.actors.at("node_probe"),actor),"Current accepted settlement actor weak identity required");
 require(r.at<uint64_t>(actor)==r.base+0xb4a11e8,"Reviewed settlement table required");virtual_matches(r,actor,0x2a8,0x3bca830);virtual_matches(r,actor,0x2b0,0x65a9260);code_matches(r,0x5b79900,"488b014885c0740b488bd1488bc8e93d9fa000c3");
 auto guid_property=f.property(actor,"NodeGuid",0x500,8),layout_property=f.property(actor,"LayoutAssetSetGuids",0x370,0x190);require(guid_property.at("type")=="Int64Property"&&layout_property.at("type")=="StructProperty","Reviewed settlement property types required");
 require(r.at<uint64_t>(actor+0x500)==0&&r.at<uint8_t>(actor+0x508)==0&&r.at<int32_t>(actor+0x480)==0&&r.at<uint32_t>(actor+0x470)==0,"Fresh nonloading full-item settlement array required");
 auto cls=f.object(actor).at("class_address").get<uint64_t>();auto field_cache=f.network_cache(cls,driver);require(field_cache.at("maximum")==16,"Exact settlement field maximum16 required");
 for(auto [name,index]:{std::pair{"LayoutAssetSetGuids",13},std::pair{"NodeGuid",14}})require(std::count_if(field_cache.at("fields").begin(),field_cache.at("fields").end(),[&](const Json& row){return row.at("name")==name&&row.at("index")==index&&row.at("kind")=="property"&&row.at("owner")=="NodeLayoutReplicator";})==1,"Exact settlement custom/scalar field mapping required");
 auto cl=f.object(cls);auto map=r.at<uint64_t>(driver+0x5c0);int count=r.at<int32_t>(driver+0x5c8),capacity=r.at<int32_t>(driver+0x5cc);require(count>0&&count<=capacity&&capacity<=8192,"Current settlement RepLayout map bounds");uint64_t rep_layout=0;
 for(int i=0;i<count;i++){auto row=map+size_t(i)*32;if(r.at<int32_t>(row)==cl.at("object_index")&&r.at<int32_t>(row+4)==cl.at("serial")){require(rep_layout==0,"Unique settlement RepLayout required");rep_layout=r.at<uint64_t>(row+8);}}
 require(rep_layout>0&&r.at<int32_t>(rep_layout+0x40)==34,"Reviewed settlement command layout required");auto command=r.at<uint64_t>(rep_layout+0x38)+32*32;
 require(r.at<uint64_t>(command)==address_of(guid_property)&&r.at<uint32_t>(command+0xc)==0x500&&r.at<uint16_t>(command+0x14)==25&&r.at<uint16_t>(command+0x16)==14&&r.at<uint8_t>(command+0x1c)==2,"Exact NodeGuid handle25/current command required");
 auto structure=r.at<uint64_t>(address_of(layout_property)+0x70);require(f.identity(structure,"ScriptStruct").at("name")=="NodeLayoutAssetSetGuids","Exact settlement script struct required");auto ops=r.at<uint64_t>(structure+0xd8);require(r.at<uint64_t>(ops)==r.base+0xb49c8d8,"Reviewed settlement custom delta ops required");virtual_matches(r,ops,0x58,0x5b76490);
 send(42,winstead_floor_content());owner.event("winstead_floor_authored",{{"connection_id",c.id},{"actor_guid",c.actors.at("node_probe").json()},{"node_guid","0x62d024b45678"},{"asset_set_guid","0x5429e761b0070000"},{"array_key",1},{"item_id",1},{"node_level",1},{"culture",0},{"season",1},{"tags",Json::array()},{"live_collision_admitted",false},{"client_acceptance_verified",false}});
}
else if(stage=="ClientSetHUD"){rpc("ClientSetHUD",53,"PlayerController");owner.send_world(c,hud_bunches(c.channel_reliable.at(3),53,maximum));}
else if(stage=="ClientRestart"){require(c.stages.contains("ClientSetHUD")&&c.stages.contains("LoadingInputLocked")&&movement_input_gate(f,controller)==1,"HUD and native loading input lock required before possession");f.property(controller,"MyHUD",0x450,8);uint64_t hud=r.at<uint64_t>(controller+0x450);require(hud&&f.identity(hud,"AoCHUDBase").at("class")=="BP_AOCHUD_C","Accepted exact gameplay HUD required");rpc("ClientRestart",45,"PlayerController");rpc("ServerAcknowledgePossession",73,"PlayerController");send(3,actor_rpc(45,maximum,object_argument(c.actors.at("pawn"))));c.ack_field=73;c.controller_max=maximum;c.possession=false;}
else{require(c.possession,"Observed exact pawn possession acknowledgement required");f.property(controller,"Pawn",0x3a8,8);f.property(controller,"AcknowledgedPawn",0x428,8);f.property(player,"Controller",0x398,8);require(r.at<uint64_t>(controller+0x3a8)==player&&r.at<uint64_t>(controller+0x428)==player&&r.at<uint64_t>(player+0x398)==controller,"Accepted mutual current possession required");if(stage=="PawnAutonomous"){require(c.stages.contains("ActivateMovement")&&movement_input_gate(f,controller)==1,"Prepared and activated server with locked input required before autonomy");auto role=f.scalar_handle(player,driver,"RemoteRole",8);require(role.at("offset_in_object")==0x180&&role.at("type")=="ByteProperty"&&r.at<uint8_t>(player+0x1f8)==1&&r.at<uint8_t>(player+0x180)==4,"Prior pawn roles must match reviewed serialization");auto pawn_cache=f.network_cache(f.object(player).at("class_address"),driver);require(pawn_cache.at("maximum")==198,"Pawn RPC maximum");require(std::any_of(pawn_cache.at("fields").begin(),pawn_cache.at("fields").end(),[](auto& v){return v.at("name")=="ServerMovePacked"&&v.at("index")==44&&v.at("owner")=="Character";}),"ServerMovePacked field44 required");send(9,role_content());}
else if(stage=="ControllerPlayerState"){auto prop=f.scalar_handle(controller,driver,"PlayerState",19);require(prop.at("offset_in_object")==0x370&&r.at<uint64_t>(controller+0x370)==0,"Current null controller PlayerState required");code_matches(r,0x3eebc80,"488bd1488b89700300004885c9740a488b0148ffa040080000c3");code_matches(r,0x44119c0,"488b0148ffa0e0050000");send(3,state_link(c.actors.at("player_state"),19));}
else if(stage=="PawnPlayerState"){auto prop=f.scalar_handle(player,driver,"PlayerState",21);require(prop.at("offset_in_object")==0x388&&r.at<uint64_t>(player+0x388)==0,"Current null pawn PlayerState required");send(9,state_link(c.actors.at("player_state"),21));}
else if(stage=="PlayerStateVerified"){f.property(controller,"PlayerState",0x370,8);f.property(player,"PlayerState",0x388,8);auto state=address_of(ps.at("actor"));require(r.at<uint64_t>(controller+0x370)==state&&r.at<uint64_t>(player+0x388)==state,"Both native PlayerState links must be accepted");}
else if(stage=="CharacterInfoExport"){require(!c.selected_character_id.empty()&&!c.selected_character_name.empty(),"Lobby-selected character identity required");auto info=f.component(player,"CharacterInformationComponent");auto identity=f.identity(info,"CharacterInfo");require(identity.at("name")=="BaseCharacterInfo"&&identity.at("class")=="PlayerInfo"&&bool_field(f,info,"bReplicates"),"Exact replicated existing PlayerInfo component required");virtual_matches(r,info,0x2a8,0x131c2f0);virtual_matches(r,info,0x2b0,0x15f4670);code_matches(r,0x131c2f0,"c20000");code_matches(r,0x15f4670,"e97b7cd2ff");Guid guid=Guid::fresh();c.actors["character_info"]=guid;auto ex=character_export(c.actors.at("pawn"),guid),empty=subobject_empty(guid);int seq=c.channel_reliable.at(9);owner.send_world(c,Json::array({{{"channel",9},{"channel_name",102},{"reliable",true},{"partial",true},{"exports",true},{"partial_flags",{1,0,0}},{"reliable_sequence",(seq+1)&1023},{"payload_hex",hex(ex.data)},{"payload_bits",ex.bits}},{{"channel",9},{"channel_name",102},{"reliable",true},{"partial",true},{"partial_flags",{0,0,1}},{"reliable_sequence",(seq+2)&1023},{"payload_hex",hex(empty.data)},{"payload_bits",empty.bits}}}));}
else if(stage=="CharacterGuid"||stage=="CharacterGuidVerified"){auto info=f.component(player,"CharacterInformationComponent");require(c.actors.contains("character_info")&&f.guid_accepted(driver,c.actors.at("character_info"),info),"Accepted CharacterInfo GUID required");verify_character_guid_layout(f,info,driver);require(c.selected_character_id.size()==32&&unhex(c.selected_character_id).size()==16,"Selected canonical character ID required");if(stage=="CharacterGuid"){for(int i=0;i<4;i++)require(r.at<uint32_t>(info+0x118+i*4)==0,"Fresh zero character Guid required");send(9,character_id(c.actors.at("character_info"),c.selected_character_id));}else{for(int i=0;i<4;i++)require(r.at<uint32_t>(info+0x118+i*4)==std::stoul(c.selected_character_id.substr(i*8,8),nullptr,16),"Native selected character Guid readback required");owner.event("character_guid_verified",{{"connection_id",c.id},{"character_id",c.selected_character_id}});}}
else if(stage=="CharacterName"||stage=="CharacterNameVerified"){auto info=f.component(player,"CharacterInformationComponent");f.identity(info,"PlayerInfo");require(c.actors.contains("character_info")&&f.guid_accepted(driver,c.actors.at("character_info"),info),"Current accepted CharacterInfo GUID required");auto prop=f.scalar_handle(info,driver,"CharacterName",8);require(prop.at("type")=="StrProperty"&&prop.at("offset_in_object")==0x130&&prop.at("element_size")==16,"Exact name string layout required");virtual_matches(r,info,0x570,0x6c2b150);if(stage=="CharacterName")send(9,character_name(c.actors.at("character_info"),c.selected_character_name));else{int count=r.at<int32_t>(info+0x138),capacity=r.at<int32_t>(info+0x13c);require(count==int(c.selected_character_name.size()+1)&&count<=capacity&&capacity<=256,"Selected native name length readback required");auto bytes=r.read(r.at<uint64_t>(info+0x130),size_t(count)*2);for(size_t i=0;i<c.selected_character_name.size();i++)require(bytes[i*2]==uint8_t(c.selected_character_name[i])&&bytes[i*2+1]==0,"Selected native character name readback mismatch");require(bytes[bytes.size()-2]==0&&bytes.back()==0,"Native name terminator required");owner.event("character_name_verified",{{"connection_id",c.id},{"character_id",c.selected_character_id},{"character_name",c.selected_character_name}});}}
else if(stage=="StatsComponentExport"){uint64_t stats=f.component(player,"StatsComponent");auto identity=f.identity(stats);require(identity.at("name")=="StatsComponent"&&identity.at("class")=="AoCStatsComponent"&&bool_field(f,stats,"bReplicates"),"Exact replicated existing stats subobject");auto vt=r.at<uint64_t>(stats);require(r.at<uint64_t>(vt+0x2a8)-r.base==0x15f4670&&r.at<uint64_t>(vt+0x2b0)-r.base==0x6132120,"Reviewed native stats receive targets");for(auto offset:{0x1198,0x11a8}){int count=r.at<int32_t>(stats+offset+8),capacity=r.at<int32_t>(stats+offset+12);require(count==0&&capacity>=0&&capacity<=4096,"Empty bounded pending stat queues required");}code_matches(r,0x15f4670,"e97b7cd2ff");Guid component=Guid::fresh();c.actors["stats_component"]=component;auto ex=stat_export(c.actors.at("pawn"),component),empty=subobject_empty(component);int seq=c.channel_reliable.at(9);Json a={{"channel",9},{"channel_name",102},{"reliable",true},{"partial",true},{"exports",true},{"partial_flags",{1,0,0}},{"reliable_sequence",(seq+1)&1023},{"payload_hex",hex(ex.data)},{"payload_bits",ex.bits}},b={{"channel",9},{"channel_name",102},{"reliable",true},{"partial",true},{"partial_flags",{0,0,1}},{"reliable_sequence",(seq+2)&1023},{"payload_hex",hex(empty.data)},{"payload_bits",empty.bits}};owner.send_world(c,Json::array({a,b}));}
else if(stage=="GameStateBeginPlay"){require(c.stages.contains("StatsComponentExport"),"Stats component must be exported before BeginPlay");auto prop=f.scalar_handle(game_state,driver,"bReplicatedHasBegunPlay",21);require(prop.at("type")=="BoolProperty"&&!bool_field(f,game_state,"bReplicatedHasBegunPlay"),"Explicit current false BeginPlay required");uint64_t level_ptr=std::stoull(level.get<std::string>(),nullptr,16);f.property(level_ptr,"OwningWorld",0xe0,8);uint64_t world=r.at<uint64_t>(level_ptr+0xe0);f.property(world,"PersistentLevel",0x50,8);require(r.at<uint64_t>(world+0x50)==level_ptr,"Current persistent level/world binding");f.property(world,"NetDriver",0x58,8);require(r.at<uint64_t>(world+0x58)==driver&&r.at<uint64_t>(driver+0x138)>0,"Gameplay client netmode driver binding");f.property(level_ptr,"WorldSettings",0x2d0,8);auto settings=r.at<uint64_t>(level_ptr+0x2d0);require(f.identity(settings,"WorldSettings").at("outer_address")==level,"Current WorldSettings owner");virtual_matches(r,driver,0x4b0,0x423d720);code_matches(r,0x423d720,"4883b938010000000f94c0c3");
require(prop.at("offset_in_object")==0x390&&prop.at("element_size")==1,"Reviewed BeginPlay storage layout");virtual_matches(r,address_of(prop),0xc8,0x170acb0);virtual_matches(r,game_state,0x898,0x5ef7800);
f.property(game_state,"NetDriverName",0x1f0,8);auto name_index=r.at<uint32_t>(game_state+0x1f0),name_number=r.at<uint32_t>(game_state+0x1f4);require(r.at<uint8_t>(r.base+0xd5edc59)==1&&name_number==0&&name_index==r.at<uint32_t>(r.base+0xd5edec0+0x14040+0x11a*4)&&f.name(name_index)=="GameNetDriver","Reviewed GameNetDriver name branch");
auto world_identity=f.identity(world,"World");require(world_identity.at("name")=="Verra_World_Master"&&f.identity(level_ptr,"Level").at("outer_address")==world_identity.at("address"),"Accepted Verra level/world chain");auto world_game_state=f.find_property(world,"GameState");require(r.at<uint64_t>(world+world_game_state.at("offset_in_object").get<unsigned>())==game_state,"World must retain the accepted GameState");
virtual_matches(r,settings,0x870,0x47bb130);virtual_matches(r,settings,0x878,0x47bb5c0);code_matches(r,0x47bb130,"48895c2410488974241848897c2420554154415541564157488d6c24c94881ec");code_matches(r,0x47bb5c0,"40534883ec20e8c5723cff488bd8f680ad010000027513488d88a8080000e81d");
for(auto rva:{0x5ef7800ull,0x56f0e70ull,0x3b847b0ull,0x4236c80ull,0x1505900ull,0x3b82890ull,0x3b82920ull}){std::ostringstream name;name<<"protocol_function_"<<std::hex<<rva<<".bin";frozen_code_matches(owner,r,rva,name.str());}frozen_code_matches(owner,r,0x4733960,"protocol_fragment_4733960.bin",160);frozen_code_matches(owner,r,0x41861f0,"protocol_fragment_41861f0.bin",8);
send(5,begin_play_content());}
else if(stage=="StatsGravity"||stage=="StatsSpeed"){require(c.stages.contains("GameStateBeginPlay")&&bool_field(f,game_state,"bReplicatedHasBegunPlay"),"Client BeginPlay readback required");uint64_t stats=f.component(player,"StatsComponent");require(c.actors.contains("stats_component")&&r.at<uint64_t>(stats+0xd08)>0,"Current initialized stats delegate required");require(f.guid_accepted(driver,c.actors.at("stats_component"),stats),"Current stats component GUID acceptance required");f.property(stats,"StatRepInt32EveryoneProxy",0xbf0,0x120);auto field_cache=f.network_cache(f.object(stats).at("class_address"),driver);require(field_cache.at("maximum")==23&&std::any_of(field_cache.at("fields").begin(),field_cache.at("fields").end(),[](auto& v){return v.at("index")==6&&v.at("name")=="StatRepInt32EveryoneProxy";}),"Exact stat replication field6/max23 required");int count=r.at<int32_t>(stats+0xd00),capacity=r.at<int32_t>(stats+0xd04);require(count>=0&&count<=capacity&&capacity<=2048,"Current stat item bounds");uint8_t flags=r.at<uint8_t>(stats+0xcf0);if(stage=="StatsGravity"){require(count==0&&flags==0,"Empty current stat array required");send(9,stat_content(c.actors.at("stats_component"),0x5429e5e8643f0018ULL,0x3f000000));}else{require(c.stages.contains("StatsGravity")&&count==1&&flags==1,"Readback gravity item required before speed");auto data=r.at<uint64_t>(stats+0xcf8);require(r.at<int32_t>(data)==1&&r.at<uint64_t>(data+16)==0x5429e5e8643f0018ULL&&r.at<uint32_t>(data+24)==0x3f000000,"Exact accepted gravity item identity/value");auto movement=f.component(player,"CharacterMovement");auto speed_property=f.find_property(movement,"MaxRunSpeed");require(speed_property.at("type")=="FloatProperty"&&speed_property.at("element_size")==4,"Live forward run speed property required");float base=r.at<float>(movement+speed_property.at("offset_in_object").get<unsigned>());require(std::isfinite(base)&&base>0&&base<=10000,"Live forward run speed bounds");float multiplier=float(owner.movement_settings.speed/base);send(9,stat_content(c.actors.at("stats_component"),0x6357c09a5679ULL,std::bit_cast<uint32_t>(multiplier),2));}}
else if(stage=="StatsResources"||stage=="StatsResourcesVerified"){
 require(c.stages.contains("StatsSpeed"),"Gravity and movement speed initialization required");auto stats=f.component(player,"StatsComponent");require(f.guid_accepted(driver,c.actors.at("stats_component"),stats),"Accepted stats component required");
 struct Resource{const char* name;uint64_t record;int scope,key,field;const char* amount;};const std::array<Resource,6> resources{{{"MaxHealth",0x631f5d125679ULL,7,3,6,"health"},{"Health",0x631f5cd65678ULL,7,4,6,"health"},{"MaxMana",0x634d486d5679ULL,7,5,6,"mana"},{"Mana",0x634d48455678ULL,7,6,6,"mana"},{"MaxStamina",0x5429e671574d01b4ULL,1,1,3,"stamina"},{"Stamina",0x5429e4778c77030cULL,1,2,3,"stamina"}}};
 auto profile=owner.config.value("lab_resources",Json{{"health",100.},{"mana",100.},{"stamina",100.}});auto cache=f.network_cache(f.object(stats).at("class_address"),driver);require(cache.at("maximum")==23,"Exact stats field maximum required");
 for(auto [field,name,offset]:{std::tuple{3,"StatRepInt32Owner",0x890},std::tuple{6,"StatRepInt32EveryoneProxy",0xbf0}}){f.property(stats,name,offset,0x120);require(std::count_if(cache.at("fields").begin(),cache.at("fields").end(),[&](const Json& row){return row.at("name")==name&&row.at("index")==field;})==1,"Current owner/everyone stat field mapping required");require(r.at<uint64_t>(stats+offset+0x118)>0,"Native initialized stat receive delegate required");}
 Json bunches=Json::array(),readback=Json::object();int seq=c.channel_reliable.at(9);
 for(auto resource:resources){float amount=profile.at(resource.amount).get<float>();require(std::isfinite(amount)&&amount>0&&amount<=1000000,"Positive finite local-test resource amount required");auto bits=std::bit_cast<uint32_t>(amount);auto native=read_resource_stat(f,stats,resource.record,resource.scope);auto item=read_replicated_stat_item(f,stats,resource.scope==1?"StatRepInt32Owner":"StatRepInt32EveryoneProxy",resource.record);
 if(stage=="StatsResources"){require(item.is_null(),"Fresh resource replication item required");auto content=stat_append(c.actors.at("stats_component"),resource.record,bits,resource.key,resource.field);bunches.push_back({{"channel",9},{"channel_name",102},{"reliable",true},{"reliable_sequence",(++seq)&1023},{"payload_hex",hex(content.data)},{"payload_bits",content.bits}});}
 else{require(item.is_object()&&item.at("item_id")==resource.key&&item.at("value_bits")==bits&&native==bits,"Resource FastArray and native getter cache acceptance required");readback[resource.name]=amount;}}
 if(stage=="StatsResources"){owner.send_world(c,bunches);c.stats_array_key=6;}else owner.event("character_resources_verified",{{"connection_id",c.id},{"source","configurable local-test profile; production defaults not recovered"},{"resources",readback}});
}
else if(stage=="PrepareMovement"){require(c.stages.contains("StatsResourcesVerified")&&c.stages.contains("CharacterNameVerified")&&bool_field(f,game_state,"bReplicatedHasBegunPlay")&&movement_input_gate(f,controller)==1,"Stats, identity, BeginPlay and loading lock required");require(r.at<uint8_t>(player+0x1f8)==1&&!owner.players.contains(c.id),"Fresh simulated pawn required before preparing server movement");owner.event("loading_native_pose_verified",{{"connection_id",c.id},{"pose",idle_loading_pose(f,player,owner.config.at("spawn").get<Vec>())}});auto p=std::make_shared<Movement>(owner.geometry,owner.config.at("spawn").get<Vec>());auto cm=f.component(player,"CharacterMovement");f.identity(cm,"AoCCharacterMovement");require(!bool_field(f,cm,"bUseSeparateBrakingFriction"),"Reviewed native friction mode required");p->ground_speeds=read_ground_speed_profile(f,cm);p->ground_friction=movement_float(f,cm,"GroundFriction");p->braking_walk=movement_float(f,cm,"BrakingDecelerationWalking");p->braking_fly=movement_float(f,cm,"BrakingDecelerationFlying");p->braking_factor=movement_float(f,cm,"BrakingFrictionFactor");p->braking_substep=movement_float(f,cm,"BrakingSubStepTime");auto capsule=f.component(player,"CapsuleComponent");auto vp=f.property(capsule,"PhysicsVolume",0x110,8);require(vp.at("type")=="WeakObjectProperty","Current physics volume weak field required");int vi=r.at<int32_t>(capsule+0x110),vs=r.at<int32_t>(capsule+0x114);require(vi>=0&&unsigned(vi)<f.count&&vs>0,"Current physics volume weak reference bounds");auto chunk=r.at<uint64_t>(f.chunks+8*(unsigned(vi)/65536));auto volume=r.at<uint64_t>(chunk+size_t(unsigned(vi)%65536)*24);auto volume_id=f.identity(volume,"PhysicsVolume");require(volume_id.at("object_index")==vi&&volume_id.at("serial")==vs,"Current physics volume weak identity required");p->flight_friction=.5*movement_float(f,volume,"FluidFriction");p->terminal_velocity=movement_float(f,volume,"TerminalVelocity");require(p->terminal_velocity>0&&p->terminal_velocity<=100000,"Positive bounded live physics-volume fall limit required");auto managers=snapshot.at("network_managers");require(managers.size()==1,"Exact native GameNetworkManager default required");auto manager=address_of(managers[0]);require(f.identity(manager,"GameNetworkManager").at("name")=="Default__GameNetworkManager","Current network manager identity required");
 p->timing.detection=bool_field(f,manager,"bMovementTimeDiscrepancyDetection");p->timing.resolution=bool_field(f,manager,"bMovementTimeDiscrepancyResolution");p->timing.force_corrections=bool_field(f,manager,"bMovementTimeDiscrepancyForceCorrectionsDuringResolution");
 p->timing.max_move_delta=float(movement_float(f,manager,"MaxMoveDeltaTime"));p->timing.max_margin=float(movement_float(f,manager,"MovementTimeDiscrepancyMaxTimeMargin"));auto minimum=f.find_property(manager,"MovementTimeDiscrepancyMinTimeMargin");require(minimum.at("type")=="FloatProperty","Native negative discrepancy margin field required");p->timing.min_margin=r.at<float>(manager+minimum.at("offset_in_object").get<unsigned>());
 p->timing.rate=float(movement_float(f,manager,"MovementTimeDiscrepancyResolutionRate"));p->timing.drift=float(movement_float(f,manager,"MovementTimeDiscrepancyDriftAllowance"));p->timing.global_multiplier=r.at<float>(r.base+0xd26eedc);p->timing.actor_dilation=float(movement_float(f,player,"CustomTimeDilation"));
 auto level_ptr=std::stoull(level.get<std::string>(),nullptr,16);f.property(level_ptr,"WorldSettings",0x2d0,8);auto settings=r.at<uint64_t>(level_ptr+0x2d0);auto dilation=movement_float(f,settings,"TimeDilation"),demo=movement_float(f,settings,"DemoPlayTimeDilation");require(dilation==1&&demo==1&&p->timing.actor_dilation==1,"Reviewed unit effective dilation required");p->timing.effective_dilation=1;
 p->falling_profile=read_falling_profile(f,player,cm,volume,settings);p->gravity=p->falling_profile.at("effective_gravity");p->jump_velocity=p->falling_profile.at("jump_velocity");
 p->air_control=p->falling_profile.at("air_control");p->air_control_boost=p->falling_profile.at("air_control_boost");p->air_control_boost_threshold=p->falling_profile.at("air_control_boost_threshold");p->falling_friction=p->falling_profile.at("falling_friction");p->braking_fall=p->falling_profile.at("braking_fall");
 owner.event("native_falling_profile_verified",{{"connection_id",c.id},{"profile",p->falling_profile},{"pid",r.pid},{"process_created_filetime",r.created}});

 p->timing.reset_interval=float(movement_float(f,cm,"MinTimeBetweenTimeStampResets"));p->max_step=movement_float(f,cm,"MaxSimulationTimeStep");auto iterations=f.find_property(cm,"MaxSimulationIterations");require(iterations.at("type")=="IntProperty","Native iteration count required");p->max_simulation_iterations=r.at<int32_t>(cm+iterations.at("offset_in_object").get<unsigned>());
 require(p->timing.max_move_delta>0&&std::max(p->timing.global_multiplier,1.f)*p->timing.max_move_delta<=2&&p->timing.min_margin<=0&&std::isfinite(p->timing.min_margin)&&p->timing.reset_interval==240&&p->max_step>0&&p->max_simulation_iterations>0&&p->max_simulation_iterations<=64,"Native timing configuration bounds");p->timing.enabled=true;
 p->native_locomotion=true;p->budget=.5;p->max_interval=.5;p->floor_clearance=2.15;auto floor=p->floor(p->position[0],p->position[1]);require(floor.has_value(),"Verified spawn collision support required");p->position[2]=*floor;p->configure(owner.movement_settings);p->recover_spawn(owner.config.at("spawn").get<Vec>());owner.players[c.id]=p;owner.trails[c.id]={p->position};}
else if(stage=="NativeMovementReady"){
 require(c.stages.contains("PawnAutonomous")&&c.stages.contains("ActivateMovement")&&movement_input_gate(f,controller)==1&&r.at<uint8_t>(player+0x1f8)==2,"Ready autonomous pawn with input still locked required");
 auto pose=idle_loading_pose(f,player,owner.config.at("spawn").get<Vec>(),true);auto contact=loading_floor_contact(f,f.component(player,"CharacterMovement"));owner.event("native_movement_ready",{{"connection_id",c.id},{"pose",pose},{"floor",contact}});
}
else if(stage=="GameplayPresentationReady"){
 require(c.stages.contains("NativeMovementReady")&&movement_input_gate(f,controller)==1&&r.at<uint8_t>(player+0x1f8)==2,"Native floor readiness and loading lock required for presentation release");
 auto client=owner.client_process.state();require(client.value("running",false)&&client.at("pid")==r.pid&&client.value("gameplay_visible",false)&&client.value("gameplay_visible_at",0.)>=client.value("world_loaded_at",0.)&&client.value("world_loaded_at",0.)>=c.handshake_time,"Current-world loading screen dismissal required before input release");
 idle_loading_pose(f,player,owner.config.at("spawn").get<Vec>(),true);loading_floor_contact(f,f.component(player,"CharacterMovement"));
 owner.event("gameplay_presentation_released",{{"connection_id",c.id},{"source","current launched client loading-screen visibility log after Verra map completion"},{"gameplay_visible_at",client.at("gameplay_visible_at")},{"onscreen_rendering_requires_screenshot",true}});
}
else if(stage=="PawnPresentationReady"){
 require(c.stages.contains("PrepareMovement")&&movement_input_gate(f,controller)==1&&r.at<uint8_t>(player+0x1f8)==1,"Locked prepared simulated pawn required for presentation readiness");
 auto mesh=f.component(player,"Mesh");auto identity=f.identity(mesh,"SkeletalMeshComponent");uint64_t asset=0;
 for(auto name:{"SkeletalMesh","SkinnedAsset"}){auto property=f.find_property(mesh,name);require(property.at("type")=="ObjectProperty"&&property.at("element_size")==8,"Current reflected character mesh asset required");auto pointer=r.at<uint64_t>(mesh+property.at("offset_in_object").get<unsigned>());if(pointer){auto current=f.identity(pointer,"SkeletalMesh");if(asset)require(asset==pointer,"Character mesh asset bindings disagree");asset=pointer;}}
 require(asset&&!bool_field(f,player,"bHidden")&&bool_field(f,mesh,"bVisible")&&!bool_field(f,mesh,"bHiddenInGame"),"Visible character mesh with accepted skeletal asset required");
 owner.event("pawn_presentation_ready",{{"connection_id",c.id},{"mesh",identity},{"asset",f.identity(asset,"SkeletalMesh")},{"native_visibility_flags",true},{"onscreen_rendering_requires_screenshot",true}});
}
else if(stage=="ActivateMovement"){
 require(c.stages.contains("PrepareMovement")&&owner.players.contains(c.id)&&movement_input_gate(f,controller)==1&&r.at<uint8_t>(player+0x1f8)==1,"Prepared movement and locked simulated pawn required before activation");
 require(!owner.config.value("initialize_winstead_floor",false)||c.stages.contains("WinsteadCollisionAdmitted"),"Native floor and private collision required before movement activation");
 require(c.speed_synced==owner.players.at(c.id)->speed,"Native speed acknowledgement required before movement activation");
 require(c.stages.contains("PawnPresentationReady"),"Native pawn mesh readiness required before autonomy");idle_loading_pose(f,player,owner.config.at("spawn").get<Vec>());owner.event("movement_ready_before_autonomy",{{"connection_id",c.id},{"native_role",1},{"native_input_counter",1},{"tiles",owner.players.at(c.id)->world->tiles.size()}});
}
else throw std::runtime_error("Unknown fixed initialization stage");}
r.verify_alive();c.stages.insert(stage);owner.event("initialization_stage_authored",{{"connection_id",c.id},{"stage",stage},{"client_proof",r.proof()},{"dispatch_verified",true},{"client_acceptance_requires_readback",true}});
}
}
