#include "ashes/backend.hpp"
#include <sstream>
#include <bit>
namespace ashes {
static uint64_t address_of(const Json& j){return std::stoull(j.at("address").get<std::string>(),nullptr,16);}
static double movement_float(Reflection& f,uint64_t component,const std::string& name){auto p=f.find_property(component,name);require(p.at("type")=="FloatProperty"&&p.at("element_size")==4,"Native movement scalar required");double value=f.r.at<float>(component+p.at("offset_in_object").get<unsigned>());require(std::isfinite(value)&&value>=0&&value<=100000,"Native movement scalar bounds");return value;}
static void code_matches(ProcessReader& r,uint64_t rva,const std::string& value){auto expected=unhex(value);require(r.read(r.base+rva,expected.size())==expected,"Reviewed code bytes changed");}
static void virtual_matches(ProcessReader& r,uint64_t object,size_t offset,uint64_t rva){require(r.at<uint64_t>(r.at<uint64_t>(object)+offset)==r.base+rva,"Reviewed current virtual target changed");}
static void frozen_code_matches(Backend& owner,ProcessReader& r,uint64_t rva,const std::string& file,size_t size=0){auto expected=read_file(owner.root/"data/client-proofs"/file);if(size){require(expected.size()>=size,"Frozen code range truncated");expected.resize(size);}require(!expected.empty()&&r.read(r.base+rva,expected.size())==expected,"Current code differs from frozen reviewed range");}
static bool bool_field(Reflection& f,uint64_t actor,const std::string& name){auto p=f.find_property(actor,name);require(p.at("type")=="BoolProperty","Reflected BoolProperty required");auto data=f.r.read(address_of(p)+0x70,4);require(data[0]==1&&data[3]>0,"Reflected bool scalar mask");return (f.r.at<uint8_t>(actor+p.at("offset_in_object").get<unsigned>()+data[1])&data[3])!=0;}
static Json accepted(const Json& snapshot,Guid guid,const std::string& cls){std::vector<Json> matches;for(auto& m:snapshot.at("network_guid_actor_matches"))if(m.at("guid")==guid.json())matches.push_back(m);require(matches.size()==1,"Exactly one current network GUID match required");auto m=matches.front();require(m.at("actor").at("class")==cls&&m.at("weak_object_index")==m.at("actor").at("object_index")&&m.at("weak_object_serial").get<int>()>0,"Accepted actor weak identity/class mismatch");return m;}
void dispatch_stage(Backend& owner,Connection& c,const Json& snapshot,const std::string& stage){require(!c.stages.contains(stage),"Initialization stage already consumed");ProcessReader r(owner.attached.at("pid"),owner.config.at("client_exe").get<std::string>(),owner.config.at("client_sha256"));verify_evidence(r.proof(),snapshot);Reflection f(r);auto pc=accepted(snapshot,c.actors.at("controller"),"AoCPlayerControllerBP_C"),pawn=accepted(snapshot,c.actors.at("pawn"),"PlayerPawn_C"),gs=accepted(snapshot,c.actors.at("game_state"),"AoCGameStateBP_C"),ps=accepted(snapshot,c.actors.at("player_state"),"AoCPlayerStateBP_C");auto cache=pc.at("guid_cache");require(cache==pawn.at("guid_cache")&&cache==gs.at("guid_cache")&&cache==ps.at("guid_cache"),"All initialized actors must share current GUID cache");auto level=pc.at("actor").at("outer_address");for(auto m:{pawn,gs,ps})require(m.at("actor").at("outer_address")==level,"Actors must share accepted level");uint64_t controller=address_of(pc.at("actor")),player=address_of(pawn.at("actor")),game_state=address_of(gs.at("actor"));for(auto m:{pc,pawn,gs,ps}){auto live=f.identity(address_of(m.at("actor")));require(live.at("object_index")==m.at("weak_object_index")&&live.at("serial")==m.at("weak_object_serial"),"Current actor lifetime changed");}
uint64_t driver=0;for(auto& d:snapshot.at("net_drivers"))if(d.value("guid_cache","")==cache.get<std::string>()){require(driver==0,"Unique owning net driver required");driver=address_of(d);}require(driver>0,"Owning current net driver missing");auto class_cache=f.network_cache(f.object(controller).at("class_address"),driver);int maximum=class_cache.at("maximum");require(maximum==1032,"Exact controller class RPC maximum required");auto rpc=[&](const std::string& name,int index,const std::string& cls){auto fields=class_cache.at("fields");require(std::count_if(fields.begin(),fields.end(),[&](auto& v){return v.at("name")==name&&v.at("index")==index&&v.at("owner")==cls&&v.at("kind")=="function";})==1,"Exact live function cache field required "+name);};auto send=[&](int channel,const Bits& b){owner.send_world(c,Json::array({{{"channel",channel},{"channel_name",102},{"reliable",true},{"reliable_sequence",(c.channel_reliable.at(channel)+1)&1023},{"payload_hex",hex(b.data)},{"payload_bits",b.bits}}}));};
if(stage=="ClientSetHUD"){rpc("ClientSetHUD",53,"PlayerController");owner.send_world(c,hud_bunches(c.channel_reliable.at(3),53,maximum));}
else if(stage=="ClientRestart"){require(c.stages.contains("ClientSetHUD"),"HUD export stage required");f.property(controller,"MyHUD",0x450,8);uint64_t hud=r.at<uint64_t>(controller+0x450);require(hud&&f.identity(hud,"AoCHUDBase").at("class")=="BP_AOCHUD_C","Accepted exact gameplay HUD required");rpc("ClientRestart",45,"PlayerController");rpc("ServerAcknowledgePossession",73,"PlayerController");send(3,actor_rpc(45,maximum,object_argument(c.actors.at("pawn"))));c.ack_field=73;c.controller_max=maximum;c.possession=false;}
else{require(c.possession,"Observed exact pawn possession acknowledgement required");f.property(controller,"Pawn",0x3a8,8);f.property(controller,"AcknowledgedPawn",0x428,8);f.property(player,"Controller",0x398,8);require(r.at<uint64_t>(controller+0x3a8)==player&&r.at<uint64_t>(controller+0x428)==player&&r.at<uint64_t>(player+0x398)==controller,"Accepted mutual current possession required");if(stage=="PawnAutonomous"){auto role=f.scalar_handle(player,driver,"RemoteRole",8);require(role.at("offset_in_object")==0x180&&role.at("type")=="ByteProperty"&&r.at<uint8_t>(player+0x1f8)==1&&r.at<uint8_t>(player+0x180)==4,"Prior pawn roles must match reviewed serialization");auto pawn_cache=f.network_cache(f.object(player).at("class_address"),driver);require(pawn_cache.at("maximum")==198,"Pawn RPC maximum");require(std::any_of(pawn_cache.at("fields").begin(),pawn_cache.at("fields").end(),[](auto& v){return v.at("name")=="ServerMovePacked"&&v.at("index")==44&&v.at("owner")=="Character";}),"ServerMovePacked field44 required");send(9,role_content());}
else if(stage=="ControllerPlayerState"){auto prop=f.scalar_handle(controller,driver,"PlayerState",19);require(prop.at("offset_in_object")==0x370&&r.at<uint64_t>(controller+0x370)==0,"Current null controller PlayerState required");code_matches(r,0x3eebc80,"488bd1488b89700300004885c9740a488b0148ffa040080000c3");code_matches(r,0x44119c0,"488b0148ffa0e0050000");send(3,state_link(c.actors.at("player_state"),19));}
else if(stage=="PawnPlayerState"){auto prop=f.scalar_handle(player,driver,"PlayerState",21);require(prop.at("offset_in_object")==0x388&&r.at<uint64_t>(player+0x388)==0,"Current null pawn PlayerState required");send(9,state_link(c.actors.at("player_state"),21));}
else if(stage=="StatsComponentExport"){uint64_t stats=f.component(player,"StatsComponent");auto identity=f.identity(stats);require(identity.at("name")=="StatsComponent"&&identity.at("class")=="AoCStatsComponent"&&bool_field(f,stats,"bReplicates"),"Exact replicated existing stats subobject");auto vt=r.at<uint64_t>(stats);require(r.at<uint64_t>(vt+0x2a8)-r.base==0x15f4670&&r.at<uint64_t>(vt+0x2b0)-r.base==0x6132120,"Reviewed native stats receive targets");for(auto offset:{0x1198,0x11a8}){int count=r.at<int32_t>(stats+offset+8),capacity=r.at<int32_t>(stats+offset+12);require(count==0&&capacity>=0&&capacity<=4096,"Empty bounded pending stat queues required");}code_matches(r,0x15f4670,"e97b7cd2ff");Guid component=Guid::fresh();c.actors["stats_component"]=component;auto ex=stat_export(c.actors.at("pawn"),component),empty=subobject_empty(component);int seq=c.channel_reliable.at(9);Json a={{"channel",9},{"channel_name",102},{"reliable",true},{"partial",true},{"exports",true},{"partial_flags",{1,0,0}},{"reliable_sequence",(seq+1)&1023},{"payload_hex",hex(ex.data)},{"payload_bits",ex.bits}},b={{"channel",9},{"channel_name",102},{"reliable",true},{"partial",true},{"partial_flags",{0,0,1}},{"reliable_sequence",(seq+2)&1023},{"payload_hex",hex(empty.data)},{"payload_bits",empty.bits}};owner.send_world(c,Json::array({a,b}));}
else if(stage=="GameStateBeginPlay"){require(c.stages.contains("StatsComponentExport"),"Stats component must be exported before BeginPlay");auto prop=f.scalar_handle(game_state,driver,"bReplicatedHasBegunPlay",21);require(prop.at("type")=="BoolProperty"&&!bool_field(f,game_state,"bReplicatedHasBegunPlay"),"Explicit current false BeginPlay required");uint64_t level_ptr=std::stoull(level.get<std::string>(),nullptr,16);f.property(level_ptr,"OwningWorld",0xe0,8);uint64_t world=r.at<uint64_t>(level_ptr+0xe0);f.property(world,"PersistentLevel",0x50,8);require(r.at<uint64_t>(world+0x50)==level_ptr,"Current persistent level/world binding");f.property(world,"NetDriver",0x58,8);require(r.at<uint64_t>(world+0x58)==driver&&r.at<uint64_t>(driver+0x138)>0,"Gameplay client netmode driver binding");f.property(level_ptr,"WorldSettings",0x2d0,8);auto settings=r.at<uint64_t>(level_ptr+0x2d0);require(f.identity(settings,"WorldSettings").at("outer_address")==level,"Current WorldSettings owner");virtual_matches(r,driver,0x4b0,0x423d720);code_matches(r,0x423d720,"4883b938010000000f94c0c3");
require(prop.at("offset_in_object")==0x390&&prop.at("element_size")==1,"Reviewed BeginPlay storage layout");virtual_matches(r,address_of(prop),0xc8,0x170acb0);virtual_matches(r,game_state,0x898,0x5ef7800);
f.property(game_state,"NetDriverName",0x1f0,8);auto name_index=r.at<uint32_t>(game_state+0x1f0),name_number=r.at<uint32_t>(game_state+0x1f4);require(r.at<uint8_t>(r.base+0xd5edc59)==1&&name_number==0&&name_index==r.at<uint32_t>(r.base+0xd5edec0+0x14040+0x11a*4)&&f.name(name_index)=="GameNetDriver","Reviewed GameNetDriver name branch");
auto world_identity=f.identity(world,"World");require(world_identity.at("name")=="Verra_World_Master"&&f.identity(level_ptr,"Level").at("outer_address")==world_identity.at("address"),"Accepted Verra level/world chain");auto world_game_state=f.find_property(world,"GameState");require(r.at<uint64_t>(world+world_game_state.at("offset_in_object").get<unsigned>())==game_state,"World must retain the accepted GameState");
virtual_matches(r,settings,0x870,0x47bb130);virtual_matches(r,settings,0x878,0x47bb5c0);code_matches(r,0x47bb130,"48895c2410488974241848897c2420554154415541564157488d6c24c94881ec");code_matches(r,0x47bb5c0,"40534883ec20e8c5723cff488bd8f680ad010000027513488d88a8080000e81d");
for(auto rva:{0x5ef7800ull,0x56f0e70ull,0x3b847b0ull,0x4236c80ull,0x1505900ull,0x3b82890ull,0x3b82920ull}){std::ostringstream name;name<<"protocol_function_"<<std::hex<<rva<<".bin";frozen_code_matches(owner,r,rva,name.str());}frozen_code_matches(owner,r,0x4733960,"protocol_fragment_4733960.bin",160);frozen_code_matches(owner,r,0x41861f0,"protocol_fragment_41861f0.bin",8);
send(5,begin_play_content());}
else if(stage=="StatsGravity"||stage=="StatsSpeed"){require(c.stages.contains("GameStateBeginPlay")&&bool_field(f,game_state,"bReplicatedHasBegunPlay"),"Client BeginPlay readback required");uint64_t stats=f.component(player,"StatsComponent");require(c.actors.contains("stats_component")&&r.at<uint64_t>(stats+0xd08)>0,"Current initialized stats delegate required");require(f.guid_accepted(driver,c.actors.at("stats_component"),stats),"Current stats component GUID acceptance required");f.property(stats,"StatRepInt32EveryoneProxy",0xbf0,0x120);auto field_cache=f.network_cache(f.object(stats).at("class_address"),driver);require(field_cache.at("maximum")==23&&std::any_of(field_cache.at("fields").begin(),field_cache.at("fields").end(),[](auto& v){return v.at("index")==6&&v.at("name")=="StatRepInt32EveryoneProxy";}),"Exact stat replication field6/max23 required");int count=r.at<int32_t>(stats+0xd00),capacity=r.at<int32_t>(stats+0xd04);require(count>=0&&count<=capacity&&capacity<=2048,"Current stat item bounds");uint8_t flags=r.at<uint8_t>(stats+0xcf0);if(stage=="StatsGravity"){require(count==0&&flags==0,"Empty current stat array required");send(9,stat_content(c.actors.at("stats_component"),0x5429e5e8643f0018ULL,0x3f000000));}else{require(c.stages.contains("StatsGravity")&&count==1&&flags==1,"Readback gravity item required before speed");auto data=r.at<uint64_t>(stats+0xcf8);require(r.at<int32_t>(data)==1&&r.at<uint64_t>(data+16)==0x5429e5e8643f0018ULL&&r.at<uint32_t>(data+24)==0x3f000000,"Exact accepted gravity item identity/value");auto movement=f.component(player,"CharacterMovement");auto speed_property=f.find_property(movement,"MaxRunSpeed");require(speed_property.at("type")=="FloatProperty"&&speed_property.at("element_size")==4,"Live forward run speed property required");float base=r.at<float>(movement+speed_property.at("offset_in_object").get<unsigned>());require(std::isfinite(base)&&base>0&&base<=10000,"Live forward run speed bounds");float multiplier=float(owner.movement_settings.speed/base);send(9,stat_content(c.actors.at("stats_component"),0x6357c09a5679ULL,std::bit_cast<uint32_t>(multiplier),2));}}
else if(stage=="ActivateMovement"){require(c.stages.contains("PawnAutonomous")&&c.stages.contains("StatsSpeed")&&bool_field(f,game_state,"bReplicatedHasBegunPlay"),"Autonomy, stats and BeginPlay required");require(r.at<uint8_t>(player+0x1f8)==2,"Client AutonomousProxy readback required");auto p=std::make_shared<Movement>(owner.geometry,owner.config.at("spawn").get<Vec>());auto cm=f.component(player,"CharacterMovement");f.identity(cm,"AoCCharacterMovement");require(!bool_field(f,cm,"bUseSeparateBrakingFriction"),"Reviewed native friction mode required");p->ground_friction=movement_float(f,cm,"GroundFriction");p->braking_walk=movement_float(f,cm,"BrakingDecelerationWalking");p->braking_fly=movement_float(f,cm,"BrakingDecelerationFlying");p->braking_factor=movement_float(f,cm,"BrakingFrictionFactor");p->braking_substep=movement_float(f,cm,"BrakingSubStepTime");auto capsule=f.component(player,"CapsuleComponent");auto vp=f.property(capsule,"PhysicsVolume",0x110,8);require(vp.at("type")=="WeakObjectProperty","Current physics volume weak field required");int vi=r.at<int32_t>(capsule+0x110),vs=r.at<int32_t>(capsule+0x114);require(vi>=0&&unsigned(vi)<f.count&&vs>0,"Current physics volume weak reference bounds");auto chunk=r.at<uint64_t>(f.chunks+8*(unsigned(vi)/65536));auto volume=r.at<uint64_t>(chunk+size_t(unsigned(vi)%65536)*24);auto volume_id=f.identity(volume,"PhysicsVolume");require(volume_id.at("object_index")==vi&&volume_id.at("serial")==vs,"Current physics volume weak identity required");p->flight_friction=.5*movement_float(f,volume,"FluidFriction");p->native_locomotion=true;p->budget=.5;p->max_interval=.5;p->floor_clearance=2.15;auto floor=p->floor(p->position[0],p->position[1]);require(floor.has_value(),"Verified spawn collision support required");p->position[2]=*floor;p->configure(owner.movement_settings);owner.players[c.id]=p;owner.trails[c.id]={p->position};}
else throw std::runtime_error("Unknown fixed initialization stage");}
r.verify_alive();c.stages.insert(stage);owner.event("initialization_stage_authored",{{"connection_id",c.id},{"stage",stage},{"client_proof",r.proof()},{"dispatch_verified",true},{"client_acceptance_requires_readback",true}});
}
}
